"use client";

import { cn } from "@pinky-ui/components";
import type { ReactNode } from "react";

type LayoutStudy = { id: string; label: string; description: string; kind: "hero" | "header" | "media" | "rail" | "feed" | "mosaic" | "focus" | "layered" | "story" | "context" };

const STUDIES: LayoutStudy[] = [
  { id: "editorial-mobile-hero", label: "Editorial Mobile Hero", description: "A narrow opening with one clear reading gesture and room for the subject to breathe.", kind: "hero" },
  { id: "collapsing-editorial-header", label: "Collapsing Editorial Header", description: "The title yields to section context without losing the current place in the story.", kind: "header" },
  { id: "full-bleed-media-header", label: "Full-Bleed Media Header", description: "Media reaches the edge while the reading title remains anchored below.", kind: "media" },
  { id: "horizontal-peek-rail", label: "Horizontal Peek Rail", description: "The next item is intentionally visible so the collection explains itself without arrows.", kind: "rail" },
  { id: "magazine-feed", label: "Magazine Feed", description: "Alternating lead stories make hierarchy visible before the reader opens anything.", kind: "feed" },
  { id: "mobile-mosaic-feed", label: "Mobile Mosaic Feed", description: "An irregular rhythm keeps a small-screen collection from becoming a flat stack.", kind: "mosaic" },
  { id: "focus-feed", label: "Focus Feed", description: "One item owns the reading frame while nearby items stay as quiet wayfinding.", kind: "focus" },
  { id: "layered-mobile-collection", label: "Layered Mobile Collection", description: "Depth preserves relationship without turning every surface into a floating card.", kind: "layered" },
  { id: "edge-to-edge-story", label: "Edge-to-Edge Story", description: "A story crosses the viewport edge while controls remain reachable in the flow.", kind: "story" },
  { id: "sticky-context-header", label: "Sticky Context Header", description: "The active collection label stays close while the content below continues to move.", kind: "context" },
];

export function MobileLayoutShowcase() {
  return <div className="space-y-5">{STUDIES.map((study, index) => <article key={study.id} className={cn("grid gap-5 border-t border-line py-6 sm:grid-cols-[minmax(11rem,0.7fr)_minmax(0,1.3fr)] sm:items-center sm:gap-8", (index === 0 || index === 2 || index === 8) && "sm:py-9")}><div><p className="font-mono text-[0.62rem] tracking-[0.16em] text-ink-500 uppercase">{String(index + 1).padStart(2, "0")} / mobile layout</p><h3 className="mt-2 font-display text-xl font-semibold tracking-tight">{study.label}</h3><p className="mt-2 max-w-sm text-sm leading-relaxed text-ink-700">{study.description}</p></div><LayoutSurface kind={study.kind} wide={index === 0 || index === 2 || index === 8} /></article>)}</div>;
}

function LayoutSurface({ kind, wide }: { kind: LayoutStudy["kind"]; wide: boolean }) {
  return <div className={cn("relative min-h-44 overflow-hidden rounded-[26px] border border-line bg-white/75 p-3 shadow-soft", wide && "min-h-52")}>{kind === "hero" ? <HeroLayout /> : null}{kind === "header" ? <HeaderLayout /> : null}{kind === "media" ? <MediaLayout /> : null}{kind === "rail" ? <RailLayout /> : null}{kind === "feed" ? <FeedLayout /> : null}{kind === "mosaic" ? <MosaicLayout /> : null}{kind === "focus" ? <FocusLayout /> : null}{kind === "layered" ? <LayeredLayout /> : null}{kind === "story" ? <StoryLayout /> : null}{kind === "context" ? <ContextLayout /> : null}</div>;
}

function MiniLabel({ children }: { children: ReactNode }) { return <span className="font-mono text-[0.56rem] tracking-[0.14em] text-ink-500 uppercase">{children}</span>; }
function HeroLayout() { return <div className="relative grid min-h-44 items-end overflow-hidden rounded-[20px] bg-[linear-gradient(135deg,var(--color-blush-100),var(--color-cloud-100))] p-5"><div className="absolute right-5 top-5 size-20 rounded-full border border-white/75 bg-white/35" /><div className="relative max-w-[18rem]"><MiniLabel>Field note / 01</MiniLabel><p className="mt-3 font-display text-2xl font-semibold leading-tight">A small screen can still open slowly.</p><p className="mt-3 text-xs text-ink-700">One subject, one useful next gesture.</p></div></div>; }
function HeaderLayout() { return <div className="space-y-3 rounded-[20px] bg-cloud-50 p-4"><div className="flex items-center justify-between border-b border-line pb-3"><MiniLabel>Reading / 02</MiniLabel><span className="text-xs text-ink-500">03 / 06</span></div><div className="grid grid-cols-[1fr_auto] items-end gap-4"><div><p className="font-display text-xl font-semibold">The header yields.</p><p className="mt-1 text-xs text-ink-600">Context stays; ornament recedes.</p></div><span className="size-10 rounded-full bg-blush-100" /></div></div>; }
function MediaLayout() { return <div className="overflow-hidden rounded-[20px] bg-ink-900 text-milk"><div className="h-28 bg-[linear-gradient(135deg,var(--color-cloud-300),var(--color-blush-200),var(--color-ink-900))]" /><div className="grid gap-1 p-4"><MiniLabel>Still / moving image</MiniLabel><p className="font-display text-xl font-semibold">Media reaches the edge.</p><span className="mt-2 text-xs text-white/70">The title stays in the reading flow.</span></div></div>; }
function RailLayout() { return <div className="overflow-hidden rounded-[20px] bg-cloud-50 p-4"><div className="flex items-end justify-between"><div><MiniLabel>Collection / 04</MiniLabel><p className="mt-2 font-display text-lg font-semibold">Leave a little next.</p></div><span className="text-xs text-ink-500">Swipe →</span></div><div className="mt-4 flex gap-3 overflow-hidden"><div className="min-w-[11rem] rounded-[18px] bg-white p-4"><span className="block h-14 rounded-[14px] bg-blush-100" /><p className="mt-3 text-sm font-medium">First object</p></div><div className="min-w-[11rem] rounded-[18px] bg-white p-4"><span className="block h-14 rounded-[14px] bg-cloud-200" /><p className="mt-3 text-sm font-medium">Next object</p></div></div></div>; }
function FeedLayout() { return <div className="grid gap-3 sm:grid-cols-[1.25fr_0.75fr]"><div className="row-span-2 rounded-[20px] bg-blush-50 p-4"><MiniLabel>Lead / 05</MiniLabel><div className="mt-4 h-24 rounded-[16px] bg-white/75" /><p className="mt-3 font-display text-lg font-semibold">The lead gets a longer sentence.</p><p className="mt-2 text-xs text-ink-700">The next story can be seen without competing.</p></div><div className="rounded-[20px] bg-cloud-50 p-4"><MiniLabel>Note / 06</MiniLabel><p className="mt-4 text-sm font-medium">A short companion story.</p></div><div className="rounded-[20px] border border-line bg-white p-4"><MiniLabel>Note / 07</MiniLabel><p className="mt-4 text-sm font-medium">Another quiet entry.</p></div></div>; }
function MosaicLayout() { return <div className="grid grid-cols-6 grid-rows-3 gap-2"><div className="col-span-4 row-span-2 rounded-[18px] bg-cloud-100 p-3"><MiniLabel>01</MiniLabel><p className="mt-12 text-sm font-semibold">Large enough to lead.</p></div><div className="col-span-2 rounded-[18px] bg-blush-100 p-3"><MiniLabel>02</MiniLabel><p className="mt-4 text-xs font-medium text-ink-700">Next read</p></div><div className="col-span-2 rounded-[18px] border border-line bg-white p-3"><MiniLabel>03</MiniLabel><p className="mt-4 text-xs font-medium text-ink-700">Saved note</p></div><div className="col-span-2 rounded-[18px] bg-ink-900 p-3 text-milk"><MiniLabel>04</MiniLabel><p className="mt-4 text-xs font-medium text-milk/80">New</p></div><div className="col-span-2 rounded-[18px] bg-cloud-50 p-3"><MiniLabel>05</MiniLabel><p className="mt-4 text-xs font-medium text-ink-700">Quiet</p></div></div>; }
function FocusLayout() { return <div className="grid grid-cols-[0.34fr_1fr] gap-3 rounded-[20px] bg-cloud-50 p-3"><div className="space-y-2 pt-2"><MiniLabel>Queue</MiniLabel>{["01", "02", "03"].map((label, index) => <div key={label} className={cn("rounded-[14px] px-2 py-3 text-center font-mono text-[0.58rem]", index === 1 ? "bg-white text-ink-900 shadow-sm" : "text-ink-400")}>{label}</div>)}</div><div className="rounded-[18px] bg-white p-4"><MiniLabel>Focus / current</MiniLabel><div className="mt-5 h-16 rounded-[14px] bg-blush-100" /><p className="mt-3 font-display text-lg font-semibold">One thing gets the room.</p></div></div>; }
function LayeredLayout() { return <div className="relative min-h-40 rounded-[20px] bg-cloud-50 p-4"><div className="absolute right-5 top-5 h-24 w-28 rotate-3 rounded-[18px] border border-line bg-blush-100/80" /><div className="absolute right-10 top-9 h-24 w-28 -rotate-3 rounded-[18px] border border-line bg-white/80" /><div className="relative z-10 w-[68%] rounded-[18px] bg-white p-4 shadow-soft"><MiniLabel>Collection / depth</MiniLabel><p className="mt-3 font-display text-lg font-semibold">The stack preserves order.</p></div></div>; }
function StoryLayout() { return <div className="-mx-3 overflow-hidden rounded-[20px] bg-ink-900 text-milk"><div className="flex min-h-40 items-end bg-[linear-gradient(120deg,var(--color-ink-900),var(--color-cloud-300),var(--color-blush-200))] p-5"><div><MiniLabel>Story / 09</MiniLabel><p className="mt-3 max-w-[14rem] font-display text-2xl font-semibold leading-tight">The edge becomes part of the sentence.</p></div></div><div className="flex items-center justify-between px-5 py-3 text-xs text-white/70"><span>01 — 04</span><span>Continue reading</span></div></div>; }
function ContextLayout() { return <div className="space-y-2 rounded-[20px] bg-cloud-50 p-3"><div className="sticky top-0 flex items-center justify-between rounded-[14px] border border-line bg-white/90 px-3 py-3 backdrop-blur-sm"><span className="font-medium text-ink-900">Collections</span><MiniLabel>Context / active</MiniLabel></div>{["Editorial notes", "Saved surfaces", "Recent work"].map((label, index) => <div key={label} className={cn("rounded-[16px] p-4 text-sm", index === 0 ? "bg-blush-50 font-medium" : "bg-white")}>{label}<span className="ml-2 text-xs text-ink-500">0{index + 1}</span></div>)}</div>; }
