"use client";

import { Reorder, motion } from "motion/react";
import { useMotionEnabled } from "@pinky/primitives";
import { useRef, useState, type ReactNode } from "react";
import { cn } from "../internal/cn";
import { moveItem, type ReorderItem } from "../lists";

export function DragReorderGrid<T extends ReorderItem>({ items, onReorder, renderItem, label = "Reorder grid", columns = 3, className }: { items: T[]; onReorder: (items: T[]) => void; renderItem?: (item: T) => ReactNode; label?: string; columns?: number; className?: string }) { const [announcement, setAnnouncement] = useState(""); const from = useRef<number | null>(null); const move = (index: number, delta: number) => { const target = Math.max(0, Math.min(items.length - 1, index + delta)); if (target === index) return; onReorder(moveItem(items, index, target)); setAnnouncement(`${items[index]?.label} moved to position ${target + 1}`); }; return <><div role="list" aria-label={label} className={cn("grid gap-3", className)} style={{ gridTemplateColumns: `repeat(${columns}, minmax(0, 1fr))` }}>{items.map((item, index) => <motion.div layout={true} key={item.id} role="listitem" draggable onDragStart={() => { from.current = index; }} onDragOver={(event) => event.preventDefault()} onDrop={() => { if (from.current != null && from.current !== index) onReorder(moveItem(items, from.current, index)); from.current = null; }} className="relative rounded-2xl border border-line bg-white p-4 shadow-sm"><button type="button" aria-label={`Reorder ${item.label}`} title="Drag or use Arrow keys" onKeyDown={(event) => { const delta = event.key === "ArrowLeft" ? -1 : event.key === "ArrowRight" ? 1 : event.key === "ArrowUp" ? -columns : event.key === "ArrowDown" ? columns : 0; if (delta) { event.preventDefault(); move(index, delta); } }} className="absolute top-2 right-2 cursor-grab touch-none">⠿</button>{renderItem?.(item) ?? item.label}</motion.div>)}</div><p aria-live="polite" className="sr-only">{announcement}</p></>;
}
export function DropIndicator({ position = "between", active = true, label = "Drop here", className, children }: { position?: "before" | "after" | "between" | "inside"; active?: boolean; label?: string; className?: string; children?: ReactNode }) { return <div role="status" aria-label={active ? label : undefined} data-position={position} className={cn("pointer-events-none rounded-full bg-blush-400 transition-opacity", position === "inside" ? "h-full min-h-12 border-2 border-dashed bg-blush-50" : "h-1", active ? "opacity-100" : "opacity-0", className)}>{children}</div>; }
export function DragGhost({ children, active = true, offset = 12, className }: { children: ReactNode; active?: boolean; offset?: number; className?: string }) { const enabled = useMotionEnabled(); return <motion.div aria-hidden style={{ x: offset, y: offset }} animate={active && enabled ? { scale: 1.03, rotate: 1.5, opacity: .92 } : { scale: 1, rotate: 0, opacity: active ? .92 : 0 }} className={cn("pointer-events-none rounded-2xl bg-white shadow-xl", className)}>{children}</motion.div>; }
export type SortableChip = ReorderItem;
export function SortableChips({ items, onReorder, onRemove, onAdd, label = "Reorder tags" }: { items: SortableChip[]; onReorder: (items: SortableChip[]) => void; onRemove?: (id: string) => void; onAdd?: () => void; label?: string }) { const enabled = useMotionEnabled(); const move = (index: number, delta: number) => onReorder(moveItem(items, index, Math.max(0, Math.min(items.length - 1, index + delta)))); return <div><Reorder.Group axis="x" values={items} onReorder={onReorder} aria-label={label} className="flex flex-wrap gap-2">{items.map((item, index) => <Reorder.Item key={item.id} value={item} layout={enabled ? true : undefined} className="inline-flex items-center rounded-full border border-line bg-white"><button type="button" className="cursor-grab touch-none py-2 pl-3" aria-label={`Reorder ${item.label}`} onKeyDown={(event) => { if (event.key === "ArrowLeft" || event.key === "ArrowRight") { event.preventDefault(); move(index, event.key === "ArrowLeft" ? -1 : 1); } }}>⠿ {item.label}</button>{onRemove ? <button type="button" onClick={() => onRemove(item.id)} aria-label={`Remove ${item.label}`} className="px-3 py-2">×</button> : null}</Reorder.Item>)}{onAdd ? <li className="list-none"><button type="button" onClick={onAdd} className="rounded-full border border-dashed border-line px-3 py-2">+ Add</button></li> : null}</Reorder.Group></div>; }
