import js from "@eslint/js";
import nextPlugin from "@next/eslint-plugin-next";
import reactHooks from "eslint-plugin-react-hooks";
import tseslint from "typescript-eslint";

/**
 * Flat config. `next lint` is deprecated in Next 15, so the ESLint CLI drives
 * this directly (`npm run lint`).
 *
 * The rule set is deliberately small: correctness rules that catch real bugs —
 * above all the hooks rules, since this library's whole architecture depends on
 * effects and motion values being wired correctly — without the stylistic
 * noise that makes a linter something people learn to ignore.
 */
export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/.next/**",
      "**/out/**",
      "**/dist/**",
      "**/*.tsbuildinfo",
      // Generated by Next on every build.
      "apps/website/next-env.d.ts",
      // macOS AppleDouble sidecars. This repo lives on an exFAT volume, so the
      // OS writes a "._name" resource fork beside every file it touches. They
      // are already gitignored; ESLint would otherwise try to parse them.
      "**/._*",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  // Next's build-time detector evaluates this config file itself. Keep the
  // plugin visible outside the TypeScript-only rules block so that detector
  // does not report a false missing-plugin warning.
  {
    plugins: {
      "@next/next": nextPlugin,
    },
  },
  {
    files: ["**/*.{ts,tsx}"],
    plugins: {
      "react-hooks": reactHooks,
      "@next/next": nextPlugin,
    },
    settings: {
      // The app lives in apps/website, not at the repo root.
      next: { rootDir: "apps/website" },
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs["core-web-vitals"].rules,
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      // Motion styling legitimately needs CSS custom properties, which React's
      // CSSProperties type does not model.
      "@typescript-eslint/consistent-type-assertions": "off",
    },
  },
  {
    files: ["**/*.test.{ts,tsx}", "**/vitest.setup.ts"],
    languageOptions: {
      globals: { global: "readonly" },
    },
  },
);
