export const COMPONENT_PREVIEW_SLUGS = [
  "jelly-card",
  "liquid-card",
  "morph-card",
  "spotlight-card",
  "tilt-card",
  "magnetic-button",
  "ripple-button",
  "glow-border",
  "fluid-tabs",
  "gooey-menu",
  "floating-dock",
  "elastic-toggle",
] as const;

export const LAYOUT_PREVIEW_SLUGS = [
  "polaroid-wall",
  "stack-grid",
  "masonry-gallery",
  "draggable-card-stack",
  "expandable-bento",
  "card-fan",
  "editorial-mosaic",
  "split-screen-gallery",
  "cinematic-horizontal-gallery",
  "gallery-list-morph",
  "broken-offset-grid",
  "layered-editorial",
  "perspective-bento",
  "floating-columns",
  "curved-3d-grid",
  "helix-gallery",
  "cylinder-gallery",
  "depth-scroll-gallery",
  "spatial-card-tunnel",
  "stack-spatial",
  "infinite-spatial-canvas",
  "asymmetric-editorial-grid",
  "focus-rail",
  "split-narrative",
  "layered-collection",
  "elastic-columns",
  "progressive-mosaic",
] as const;

export const EXPLORE_PREVIEW_SLUGS = [
  ...COMPONENT_PREVIEW_SLUGS,
  ...LAYOUT_PREVIEW_SLUGS,
  "cursor-spotlight",
  "hover-image-preview",
  "lens-cursor",
  "blur-reveal",
  "spring-reveal",
  "mask-reveal",
  "stagger-reveal",
  "image-reveal",
  "liquid-loader",
  "edge-highlight",
  "surface-compression",
  "depth-shift",
  "border-travel",
  "content-swap-motion",
  "split-text-reveal",
  "word-stagger",
  "character-stagger",
  "hover-text-reveal",
  "text-scramble",
  "kinetic-underline",
  "liquid-navbar",
  "morph-menu",
  "floating-island-nav",
  "depth-hero",
  "magnetic-cta-hero",
  "soft-mesh-background",
  "interactive-gradient",
  "bubble-field",
  "spotlight-grid",
  "bubble-transition",
  "liquid-wipe-transition",
  "blur-route-transition",
  "morph-lightbox",
  "before-after",
  "expandable-media",
  "floating-media-player",
  "elastic-segmented-control",
  "morph-select",
  "tactile-range",
  "smart-dropzone",
  "hold-to-confirm",
  "inline-edit-morph",
  "inline-edit-field",
  "expanding-search",
  "validation-field",
  "progressive-form",
  "animated-number",
  "interactive-sparkline",
  "data-lens",
  "timeline-scrubber",
  "radial-meter",
  "comparison-bars",
  "filter-rail",
  "sortable-data-rows",
  "expandable-data-row",
  "selection-tray",
  "morph-toast",
  "status-pill",
  "inline-feedback",
  "action-undo-bar",
  "morph-search",
  "command-palette",
  "search-results-morph",
  "skeleton-morph",
  "shimmer-surface",
  "multi-step-progress",
  "circular-progress-morph",
  "async-button",
  "reorderable-list",
  "expandable-list-row",
  "swipe-action-row",
  "sticky-data-header",
  "row-spotlight",
  "drag-reorder-grid",
  "drop-indicator",
  "drag-ghost",
  "sortable-chips",
  "stepper",
  "progressive-disclosure",
  "swipeable-tabs",
  "pull-to-refresh",
  "edge-swipe-panel",
  "long-press-action",
  "progressive-step-workflow",
  "status-pipeline",
] as const;

export function hasComponentPreview(slug: string) {
  return COMPONENT_PREVIEW_SLUGS.includes(slug as (typeof COMPONENT_PREVIEW_SLUGS)[number]);
}

export function hasLayoutPreview(slug: string) {
  return LAYOUT_PREVIEW_SLUGS.includes(slug as (typeof LAYOUT_PREVIEW_SLUGS)[number]);
}

export function hasExplorePreview(slug: string) {
  return EXPLORE_PREVIEW_SLUGS.includes(slug as (typeof EXPLORE_PREVIEW_SLUGS)[number]);
}
