import type { Preset, PropDef, Status } from "./types";

export type ProductFamily = "media" | "forms" | "data";
export type ProductRegistryEntry = {
  slug: string; name: string; family: ProductFamily; description: string; status: Status;
  tags: string[]; interactions: string[]; builtOn: string[]; importPath: string; usage: string;
  props: PropDef[]; presets: Preset[]; demoPath: string; skill: string;
  accessibility: string[]; reducedMotion: string; performance: string[];
  whenToUse: string[]; whenNotToUse: string[]; related: string[];
};

type Config = Omit<ProductRegistryEntry, "status" | "importPath" | "demoPath" | "skill" | "props" | "presets" | "accessibility" | "reducedMotion"> & {
  component: string; primaryProp: PropDef; quiet?: Record<string, number | string | boolean>;
  accessibility?: string[]; reducedMotion?: string;
};

const entry = ({ component, primaryProp, quiet = { disabled: true }, accessibility, reducedMotion, ...item }: Config): ProductRegistryEntry => ({
  ...item,
  status: "ready",
  importPath: `import { ${component} } from "@pinky/systems";`,
  props: [primaryProp, { name: "className", type: "string", description: "Styles the outer interaction surface." }],
  presets: [{ name: "Default", description: "Restrained production behaviour.", props: {} }, { name: "Quiet", description: "Reduced intensity for dense product screens.", props: quiet }],
  demoPath: `/${item.family}#${item.slug}`,
  skill: item.slug,
  accessibility: accessibility ?? ["Keyboard and touch paths match the pointer interaction.", "Stable labels and values remain available without motion."],
  reducedMotion: reducedMotion ?? "Motion resolves immediately while semantics, focus and state remain unchanged.",
});

export const mediaSystems = [
  entry({ component: "MorphLightbox", family: "media", slug: "morph-lightbox", name: "Morph Lightbox", description: "A selected thumbnail expands into a focus-managed collection view.", tags: ["gallery", "lightbox", "media"], interactions: ["morph", "keyboard", "touch"], builtOn: ["Morph", "shared layout"], usage: `<MorphLightbox items={photos} />`, primaryProp: { name: "items", type: "MorphLightboxItem[]", description: "Labeled thumbnails and expanded media." }, performance: ["Uses host-provided lazy media and mounts only the active expanded view."], whenToUse: ["Photography and portfolio collections"], whenNotToUse: ["Arbitrary modal content or huge feeds"], related: ["expandable-media", "shared-element-transition"] }),
  entry({ component: "BeforeAfter", family: "media", slug: "before-after", name: "Before / After", description: "An aligned media comparison driven by a native range.", tags: ["comparison", "drag", "range"], interactions: ["drag", "keyboard", "touch"], builtOn: ["native range", "PressSpring"], usage: `<BeforeAfter before={before} after={after} />`, primaryProp: { name: "value", type: "number", defaultValue: "50", description: "Controlled reveal percentage." }, performance: ["One clipped overlay; no canvas or pointer-frame React loop."], whenToUse: ["Redesign, editing and restoration comparisons"], whenNotToUse: ["Unaligned or misleading images"], related: ["tactile-range", "media-lens"] }),
  entry({ component: "HoverVideoScrubber", family: "media", slug: "hover-video-scrubber", name: "Hover Video Scrubber", description: "Pointer position previews video time with keyboard and touch alternatives.", tags: ["video", "scrub", "portfolio"], interactions: ["pointer", "keyboard", "touch"], builtOn: ["HTMLVideoElement", "requestAnimationFrame"], usage: `<HoverVideoScrubber src={reel} poster={poster} label="Product reel" />`, primaryProp: { name: "preload", type: '"none" | "metadata" | "auto"', defaultValue: '"metadata"', description: "Host-controlled download strategy." }, quiet: { preload: "none", clickToPlay: false }, performance: ["Seeks the video element directly without React per pointer frame.", "Defaults to metadata rather than full preload."], whenToUse: ["A few creative or product video previews"], whenNotToUse: ["Large autoplay grids or long-form playback"], related: ["floating-media-player", "image-sequence"] }),
  entry({ component: "ImageSequence", family: "media", slug: "image-sequence", name: "Image Sequence", description: "Pointer, drag and keyboard inspection across supplied frames.", tags: ["frames", "360", "process"], interactions: ["drag", "keyboard", "touch"], builtOn: ["native images", "controlled state"], usage: `<ImageSequence frames={frames} interaction="drag" alt="Product rotation" />`, primaryProp: { name: "frames", type: "string[]", description: "Ordered image frame URLs." }, quiet: { autoplay: false, preloadCount: 2 }, performance: ["Autoplay is opt-in and preload count is capped by the consumer.", "No continuous animation runs by default."], whenToUse: ["Short product rotations and process sequences"], whenNotToUse: ["Large raw frame dumps better served by video"], related: ["hover-video-scrubber", "timeline-scrubber"] }),
  entry({ component: "ExpandableMedia", family: "media", slug: "expandable-media", name: "Expandable Media", description: "Inline media expands into a larger captioned view as the same object.", tags: ["article", "diagram", "screenshot"], interactions: ["morph", "keyboard"], builtOn: ["Morph"], usage: `<ExpandableMedia preview={image} expanded={detail} label="Architecture diagram" />`, primaryProp: { name: "preview", type: "ReactNode", description: "Inline media source surface." }, performance: ["Reuses existing Morph focus, scroll-lock and shared layout behaviour."], whenToUse: ["Article screenshots, diagrams and demonstrations"], whenNotToUse: ["Generic cards or multi-item galleries"], related: ["morph-lightbox", "morph-card"] }),
  entry({ component: "FloatingMediaPlayer", family: "media", slug: "floating-media-player", name: "Floating Media Player", description: "A host player can minimize, restore or close without becoming a streaming platform.", tags: ["player", "floating", "layout"], interactions: ["controls", "keyboard"], builtOn: ["Motion layout", "controlled state"], usage: `<FloatingMediaPlayer label="Lesson" onPlayPause={setPlaying}>{video}</FloatingMediaPlayer>`, primaryProp: { name: "mode", type: '"inline" | "floating" | "closed"', description: "Controlled player layout state." }, quiet: { defaultMode: "inline" }, performance: ["Owns layout only; playback and stream cleanup remain with the host."], whenToUse: ["Persistent nearby lessons or product demos"], whenNotToUse: ["Full streaming-player feature sets"], related: ["hover-video-scrubber"] }),
] satisfies ProductRegistryEntry[];

export const formSystems = [
  entry({ component: "ElasticSegmentedControl", family: "forms", slug: "elastic-segmented-control", name: "Elastic Segmented Control", description: "A compact radio or tab selector with one elastic active surface.", tags: ["segmented", "radio", "tabs"], interactions: ["selection", "keyboard", "touch"], builtOn: ["Fluid Tabs vocabulary", "spring vocabulary"], usage: `<ElasticSegmentedControl label="Billing" items={plans} />`, primaryProp: { name: "mode", type: '"radio" | "tabs"', defaultValue: '"radio"', description: "Semantics matching value or panel selection." }, performance: ["One shared indicator moves without layout shift."], whenToUse: ["Two to five compact product choices"], whenNotToUse: ["Primary navigation or multi-select"], related: ["fluid-tabs", "liquid-navbar"] }),
  entry({ component: "MorphSelect", family: "forms", slug: "morph-select", name: "Morph Select", description: "A labeled compact control expands into a keyboard-complete listbox.", tags: ["select", "listbox", "typeahead"], interactions: ["keyboard", "focus", "selection"], builtOn: ["listbox abstraction", "Motion"], usage: `<MorphSelect label="Format" options={formats} />`, primaryProp: { name: "options", type: "MorphSelectOption[]", description: "Short single-select option set." }, accessibility: ["Arrow, Home/End, Enter, Escape and short typeahead are supported.", "Closing restores focus to the labeled trigger."], performance: ["Options mount only while open; no large list virtualization is implied."], whenToUse: ["Short custom product option sets"], whenNotToUse: ["Long, searchable or platform-standard selects"], related: ["elastic-segmented-control"] }),
  entry({ component: "TactileRange", family: "forms", slug: "tactile-range", name: "Tactile Range", description: "A native range with quiet tactile thumb, fill and formatted value.", tags: ["slider", "range", "precision"], interactions: ["drag", "keyboard", "touch"], builtOn: ["native range", "PressSpring"], usage: `<TactileRange label="Intensity" min={0} max={100} />`, primaryProp: { name: "step", type: "number", defaultValue: "1", description: "Native keyboard and drag increment." }, performance: ["Native input owns precision and events; visual layers are transform-only."], whenToUse: ["Bounded numeric preferences"], whenNotToUse: ["Exact or unbounded numeric entry"], related: ["before-after"] }),
  entry({ component: "SmartDropzone", family: "forms", slug: "smart-dropzone", name: "Smart Dropzone", description: "A real file input with drag states and local validation hooks.", tags: ["files", "dropzone", "validation"], interactions: ["drag", "keyboard", "touch"], builtOn: ["native file input"], usage: `<SmartDropzone label="Choose images" accept="image/*" onFiles={setFiles} />`, primaryProp: { name: "accept", type: "string", description: "MIME and extension rules mirrored by local validation." }, performance: ["Does not create object URLs or claim an upload backend.", "Consumers own preview URL cleanup."], whenToUse: ["Frontend file selection and validation"], whenNotToUse: ["Pretending local acceptance means remote upload"], related: ["proximity"] }),
  entry({ component: "HoldToConfirm", family: "forms", slug: "hold-to-confirm", name: "Hold to Confirm", description: "Sustained input confirms one rare consequential action.", tags: ["destructive", "hold", "safety"], interactions: ["press", "keyboard", "touch"], builtOn: ["PressSpring", "timers"], usage: `<HoldToConfirm onConfirm={deleteProject}>Delete project</HoldToConfirm>`, primaryProp: { name: "duration", type: "number", defaultValue: "1200", description: "Required sustained intent in milliseconds." }, quiet: { duration: 900 }, accessibility: ["Space/Enter and pointer/touch share completion and cancellation rules.", "Reduced motion uses an explicit two-press confirmation."], performance: ["Timers and progress interval are cleaned on cancel and unmount."], whenToUse: ["Rare irreversible actions"], whenNotToUse: ["Ordinary save, navigation, checkout or repetitive actions"], related: ["destructive-actions"] }),
  entry({ component: "InlineEditMorph", family: "forms", slug: "inline-edit-morph", name: "Inline Edit Morph", description: "A labeled read-only value becomes a focused validated text field.", tags: ["inline-edit", "settings", "validation"], interactions: ["keyboard", "focus", "morph"], builtOn: ["Motion layout", "controlled state"], usage: `<InlineEditMorph label="Display name" value={name} onValueChange={setName} />`, primaryProp: { name: "validate", type: "(value: string) => string | null", description: "Synchronous validation that keeps invalid drafts editable." }, accessibility: ["Enter saves, Escape cancels and opening selects the input.", "Validation errors use invalid state and an alert description."], performance: ["Only the active editor mounts; layout interpolation is disabled for reduced motion."], whenToUse: ["Small profile and settings values"], whenNotToUse: ["Long-form or dependent form workflows"], related: ["morph-select"] }),
  entry({ component: "InlineEditField", family: "forms", slug: "inline-edit-field", name: "Inline Edit Field", description: "A product field keeps its label, help text and validation attached while entering edit mode.", tags: ["inline-edit", "field", "settings"], interactions: ["focus", "keyboard", "validation"], builtOn: ["controlled state", "native form"], usage: `<InlineEditField label="Workspace name" value={name} onValueChange={setName} description="Shown to collaborators." />`, primaryProp: { name: "validate", type: "(value: string) => string | null", description: "Synchronous validation for the field-level save path." }, accessibility: ["The resting value and edit action have an explicit label; Save and Cancel are real buttons.", "Escape cancels and validation is announced beside the field without removing the draft."], performance: ["Only one small native input is active; no pointer-frame work is required."], whenToUse: ["Settings and profile fields that benefit from local context"], whenNotToUse: ["Long multi-field forms or inline table cells with many dependencies"], related: ["inline-edit-morph", "validation-field"] }),
  entry({ component: "ExpandingSearch", family: "forms", slug: "expanding-search", name: "Expanding Search", description: "A compact search intent expands into an autofocus query surface without leaving the current layout.", tags: ["search", "expand", "focus"], interactions: ["focus", "keyboard", "results"], builtOn: ["AnimatePresence", "focus restoration"], usage: `<ExpandingSearch value={query} onValueChange={setQuery} results={results} />`, primaryProp: { name: "results", type: "ReactNode", description: "Optional result surface rendered below the active query." }, accessibility: ["The compact trigger exposes expanded state and opening moves focus to the labelled input.", "Escape closes the field and restores focus; Clear and Close remain keyboard reachable."], performance: ["Results mount only while the search surface is open; query changes do not run a pointer loop."], whenToUse: ["Toolbar and collection search where a full field would compete with content"], whenNotToUse: ["Primary search pages or command palettes with grouped keyboard actions"], related: ["morph-search", "command-palette"] }),
  entry({ component: "ValidationField", family: "forms", slug: "validation-field", name: "Validation Field", description: "A field communicates idle, correcting, valid, warning and invalid states as readable feedback.", tags: ["validation", "forms", "feedback"], interactions: ["focus", "input", "status"], builtOn: ["native input", "controlled state"], usage: `<ValidationField label="Email" value={email} onValueChange={setEmail} validate={validateEmail} />`, primaryProp: { name: "validate", type: "(value: string) => ValidationResult", description: "Returns a semantic status and message for the current value." }, accessibility: ["Invalid state uses aria-invalid and an adjacent status message; color is not the only signal.", "The field remains editable while correcting and status changes are announced politely."], performance: ["Validation is synchronous and host-owned; the component adds no debounce or network assumption."], whenToUse: ["Local validation where the next action depends on a field being legible and complete"], whenNotToUse: ["Remote validation that needs an async request state without a host adapter"], related: ["inline-edit-field", "morph-select"] }),
  entry({ component: "ProgressiveForm", family: "forms", slug: "progressive-form", name: "Progressive Form", description: "Completed form sections condense into context while only the next useful section opens.", tags: ["form", "progressive", "steps"], interactions: ["focus", "disclosure", "workflow"], builtOn: ["controlled state", "Motion layout"], usage: `<ProgressiveForm steps={steps} onCompletedIdsChange={setCompleted} />`, primaryProp: { name: "steps", type: "ProgressiveFormStep[]", description: "Ordered sections with content, summaries and optional completion guards." }, accessibility: ["Completed sections remain editable buttons; current content and next context have stable headings.", "Continue, Back and Complete form are explicit controls with a live completion announcement."], performance: ["Only the active section renders its form content; reduced motion preserves the same structure."], whenToUse: ["Short setup flows where completed answers should remain visible"], whenNotToUse: ["Long forms that need a full review page or arbitrary branching"], related: ["progressive-disclosure", "stepper"] }),
] satisfies ProductRegistryEntry[];

export const dataSystems = [
  entry({ component: "InteractiveLineChart", family: "data", slug: "interactive-line-chart", name: "Interactive Line Chart", description: "A calm line reading surface with snapped crosshair, direct values and keyboard point browsing.", tags: ["chart", "line", "crosshair", "reading"], interactions: ["pointer", "keyboard", "touch"], builtOn: ["SVG", "controlled index"], usage: `<InteractiveLineChart data={points} label="Weekly usage" />`, primaryProp: { name: "data", type: "VizPoint[]", description: "Ordered labelled values with optional context." }, accessibility: ["The focused plot exposes a labelled reading rail and Arrow/Home/End point navigation.", "The active value is announced beside the chart; no pointer hover is required."], performance: ["Uses one lightweight SVG and updates only the active index.", "No chart dependency or per-frame React tree is required."], whenToUse: ["Small, inspectable trends where the current point matters"], whenNotToUse: ["Large analytical datasets that need zoom, multiple axes or aggregation"], related: ["interactive-sparkline", "data-lens"] }),
  entry({ component: "RangeBrushChart", family: "data", slug: "range-brush-chart", name: "Range Brush Chart", description: "An overview and focused chart share one selected window with draggable and keyboard-adjustable bounds.", tags: ["chart", "range", "brush", "selection"], interactions: ["drag", "keyboard", "touch"], builtOn: ["SVG", "native range"], usage: `<RangeBrushChart data={history} label="Usage history" />`, primaryProp: { name: "data", type: "VizPoint[]", description: "Ordered values for the overview and focused reading." }, accessibility: ["Start and end handles are real labelled range inputs with a visible Reset range action.", "The selected window and current value remain readable when motion is reduced."], performance: ["The overview and focus use deterministic SVG geometry; no external chart engine is required.", "Pointer updates stay local to the brush and focused chart."], whenToUse: ["Short histories where overview context and local inspection belong together"], whenNotToUse: ["Unbounded time-series analysis or dense financial tooling"], related: ["timeline-scrubber", "interactive-line-chart"] }),
  entry({ component: "ComparisonChart", family: "data", slug: "comparison-chart", name: "Comparison Chart", description: "Two aligned series reveal values, direction and the gap between them at one readable point.", tags: ["chart", "comparison", "difference", "series"], interactions: ["pointer", "keyboard", "focus"], builtOn: ["SVG", "controlled index"], usage: `<ComparisonChart labels={labels} series={[productA, productB]} label="Product comparison" />`, primaryProp: { name: "series", type: "[ComparisonChartSeries, ComparisonChartSeries]", description: "Two aligned series sharing the same labels." }, accessibility: ["The reading rail publishes both values and a signed difference at the active label.", "Line style, marker shape, direct labels and text values reinforce series identity beyond colour."], performance: ["Two SVG paths and one local active index keep comparison updates bounded."], whenToUse: ["Reading a meaningful gap between two aligned measures"], whenNotToUse: ["More than two series or unrelated categories that need a table"], related: ["interactive-line-chart", "comparison-bars"] }),
  entry({ component: "AnnotatedTimeline", family: "data", slug: "annotated-timeline", name: "Annotated Timeline", description: "A trend and its meaningful events share one reading structure so change has context.", tags: ["chart", "timeline", "annotation", "events"], interactions: ["pointer", "keyboard", "touch"], builtOn: ["SVG", "semantic buttons"], usage: `<AnnotatedTimeline data={trend} annotations={events} label="Launch timeline" />`, primaryProp: { name: "annotations", type: "TimelineAnnotation[]", description: "Indexed events with concise labels and context." }, accessibility: ["Event markers are labelled buttons with focus, pressed state and a readable context panel.", "The chart still exposes Arrow/Home/End point reading when no event is selected."], performance: ["Annotations are a small set of positioned buttons; there is no timeline-sized DOM canvas."], whenToUse: ["Trends where releases, incidents or campaigns explain a change"], whenNotToUse: ["Full project planning timelines or arbitrary task scheduling"], related: ["timeline-scrubber", "interactive-line-chart"] }),
  entry({ component: "ThresholdBandChart", family: "data", slug: "threshold-band-chart", name: "Threshold / Band Chart", description: "Normal, warning and target ranges become labelled chart structure with threshold-aware reading.", tags: ["chart", "threshold", "bands", "status"], interactions: ["pointer", "keyboard", "focus"], builtOn: ["SVG", "semantic status"], usage: `<ThresholdBandChart data={latency} bands={bands} label="Response time" />`, primaryProp: { name: "bands", type: "ThresholdBand[]", description: "Ordered labelled numeric ranges with optional descriptions." }, accessibility: ["The active reading includes value and band name; the visible band list repeats numeric boundaries.", "Dashed threshold lines and a distinct marker keep state understandable without colour alone."], performance: ["Bands are static SVG regions and the active point is the only changing geometry."], whenToUse: ["Capacity, quality or response measures with meaningful operating ranges"], whenNotToUse: ["Arbitrary categorical data without numeric thresholds"], related: ["radial-meter", "interactive-line-chart"] }),
  entry({ component: "InteractiveBarRanking", family: "data", slug: "interactive-bar-ranking", name: "Interactive Bar Ranking", description: "Ranked rows can change metric and order while each item keeps its spatial identity and value.", tags: ["chart", "ranking", "sorting", "bars"], interactions: ["selection", "keyboard", "focus"], builtOn: ["Motion layout", "semantic list"], usage: `<InteractiveBarRanking items={items} metrics={metrics} label="Campaign ranking" />`, primaryProp: { name: "items", type: "BarRankingItem[]", description: "Named items with values for each selectable metric." }, accessibility: ["Metric and sort controls are semantic buttons; each ranked row exposes rank, label and value.", "Bars are paired with numbers and order, so colour is not the only signal."], performance: ["Layout motion is limited to discrete reorder events; reduced motion switches directly to the new order."], whenToUse: ["Small ranked sets where sorting is part of the reading task"], whenNotToUse: ["Large tables that need pagination, filtering or virtualization"], related: ["comparison-bars", "selection-tray"] }),
  entry({ component: "LinkedSmallMultiples", family: "data", slug: "linked-small-multiples", name: "Linked Small Multiples", description: "Several compact charts share one reading position while keeping each metric’s identity visible.", tags: ["chart", "small-multiples", "crosshair", "comparison"], interactions: ["pointer", "keyboard", "touch"], builtOn: ["SVG", "shared index"], usage: `<LinkedSmallMultiples charts={metrics} label="Metric comparison" />`, primaryProp: { name: "charts", type: "SmallMultiple[]", description: "Aligned labelled series rendered as a shared reading collection." }, accessibility: ["One focusable group moves the shared reading position with Arrow/Home/End.", "A direct value rail publishes every metric at the current label instead of making users inspect four tooltips."], performance: ["Each mini chart renders one path and one marker; selection is one shared index."], whenToUse: ["Comparing several aligned metrics without building a dashboard wall"], whenNotToUse: ["Unaligned series or charts that need independent time ranges"], related: ["interactive-line-chart", "comparison-chart"] }),
  entry({ component: "ChartTableView", family: "data", slug: "chart-table-view", name: "Chart ↔ Table View", description: "One dataset moves between an inspectable chart and a semantic table without losing selection context.", tags: ["chart", "table", "accessibility", "fallback"], interactions: ["selection", "keyboard", "responsive"], builtOn: ["SVG", "native table"], usage: `<ChartTableView data={points} label="Weekly usage" />`, primaryProp: { name: "data", type: "VizPoint[]", description: "The single ordered dataset shared by chart and table views." }, accessibility: ["Table mode uses real caption, headers, row headers and keyboard-selectable rows.", "Chart and table preserve the same selected point; mobile users get the table as a first-class reading mode."], performance: ["Chart and table share data and mount only the selected view; no duplicate chart state is required."], whenToUse: ["Product metrics where visual pattern and exact row reading both matter"], whenNotToUse: ["Decorative charts with no underlying inspectable values"], related: ["interactive-line-chart", "data-lens"] }),
  entry({ component: "AnimatedNumber", family: "data", slug: "animated-number", name: "Animated Number", description: "A locale-aware numeric update with one stable accessible final value.", tags: ["number", "kpi", "locale"], interactions: ["update"], builtOn: ["Intl.NumberFormat", "requestAnimationFrame"], usage: `<AnimatedNumber value={1503} prefix="$" locale="en-US" />`, primaryProp: { name: "decimals", type: "number", defaultValue: "0", description: "Stable locale-formatted precision." }, quiet: { duration: 250 }, accessibility: ["Visual interpolation is aria-hidden; assistive technology receives only the final value."], performance: ["Writes visual text directly rather than rendering React every frame.", "Animation frame is canceled on value change or unmount."], whenToUse: ["Occasional KPI and summary updates"], whenNotToUse: ["Constant feeds or delayed first values"], related: ["radial-meter", "comparison-bars"] }),
  entry({ component: "InteractiveSparkline", family: "data", slug: "interactive-sparkline", name: "Interactive Sparkline", description: "A dependency-free SVG trend with point inspection and textual output.", tags: ["sparkline", "svg", "trend"], interactions: ["pointer", "keyboard", "touch"], builtOn: ["SVG", "controlled index"], usage: `<InteractiveSparkline data={history} label="Revenue history" />`, primaryProp: { name: "data", type: "SparklinePoint[]", description: "Small ordered labeled value series." }, performance: ["No chart dependency and one lightweight SVG.", "Selection updates only when the nearest point changes."], whenToUse: ["Small metric histories"], whenNotToUse: ["Multi-axis or analysis-heavy charts"], related: ["data-lens", "comparison-bars"] }),
  entry({ component: "DataLens", family: "data", slug: "data-lens", name: "Data Lens", description: "Chart-agnostic pointer, touch and keyboard local inspection.", tags: ["inspection", "overlay", "chart"], interactions: ["pointer", "keyboard", "touch"], builtOn: ["slider semantics", "controlled index"], usage: `<DataLens items={points} renderLens={renderValue}>{chart}</DataLens>`, primaryProp: { name: "renderLens", type: "(item, index) => ReactNode", description: "Host-owned compact textual inspection output." }, performance: ["Does not couple to SVG, canvas or a chart library.", "Updates selection only when index changes."], whenToUse: ["Adding a consistent inspector to custom charts"], whenNotToUse: ["Charts that already provide an accessible inspector"], related: ["interactive-sparkline", "timeline-scrubber"] }),
  entry({ component: "TimelineScrubber", family: "data", slug: "timeline-scrubber", name: "Timeline Scrubber", description: "A native snapping range across labeled horizontal or vertical stops.", tags: ["timeline", "milestones", "range"], interactions: ["drag", "keyboard", "touch"], builtOn: ["native range", "controlled index"], usage: `<TimelineScrubber stops={milestones} onIndexChange={setMilestone} />`, primaryProp: { name: "stops", type: "TimelineStop[]", description: "Ordered labeled and optionally described positions." }, performance: ["Native range supplies drag and keyboard without a gesture runtime."], whenToUse: ["Media, milestone and history selection"], whenNotToUse: ["Dozens of labels or non-positional lists"], related: ["image-sequence", "data-lens"] }),
  entry({ component: "RadialMeter", family: "data", slug: "radial-meter", name: "Radial Meter", description: "A restrained semantic circular value display with optional segments.", tags: ["meter", "progress", "svg"], interactions: ["update"], builtOn: ["SVG", "Motion"], usage: `<RadialMeter value={67} label="Completion" />`, primaryProp: { name: "segments", type: "number", defaultValue: "1", description: "Optional meaningful intervals around the track." }, performance: ["Two SVG circles and one animated stroke offset."], whenToUse: ["One bounded completion or capacity value"], whenNotToUse: ["Many adjacent gauges or ambiguous scores"], related: ["animated-number", "comparison-bars"] }),
  entry({ component: "ComparisonBars", family: "data", slug: "comparison-bars", name: "Comparison Bars", description: "A small labeled dataset compared against one shared baseline.", tags: ["bars", "comparison", "baseline"], interactions: ["focus", "update"], builtOn: ["Motion width", "semantic list"], usage: `<ComparisonBars label="Plans" items={plans} />`, primaryProp: { name: "items", type: "ComparisonBarItem[]", description: "Two to six labeled values sharing one unit." }, performance: ["Simple DOM bars avoid a chart dependency.", "Reduced motion resolves widths immediately."], whenToUse: ["Current/target and compact plan comparisons"], whenNotToUse: ["Large, negative or multi-unit datasets"], related: ["radial-meter", "interactive-sparkline"] }),
  entry({ component: "FilterRail", family: "data", slug: "filter-rail", name: "Filter Rail", description: "A grouped filter rail keeps active choices, removal and result context in one compact surface.", tags: ["filter", "rail", "selection"], interactions: ["selection", "keyboard", "touch"], builtOn: ["native buttons", "controlled state"], usage: `<FilterRail groups={groups} value={filters} onValueChange={setFilters} />`, primaryProp: { name: "groups", type: "FilterRailGroup[]", description: "Grouped single-select options rendered as a responsive rail." }, accessibility: ["Each option is a real button with pressed state and a visible All reset.", "Active filters can be removed individually or cleared together on touch and keyboard."], performance: ["Only discrete selection changes update the rail; horizontal option lists stay native scrollable on small screens."], whenToUse: ["Collection and data views with a few mutually exclusive filter groups"], whenNotToUse: ["Complex boolean query builders or dozens of options"], related: ["morph-select", "selection-tray"] }),
  entry({ component: "SortableDataRows", family: "data", slug: "sortable-data-rows", name: "Sortable Data Rows", description: "Structured data rows can be reordered without losing their columns or keyboard path.", tags: ["table", "reorder", "drag"], interactions: ["drag", "keyboard", "touch"], builtOn: ["native HTML5 drag-and-drop", "keyboard movement"], usage: `<SortableDataRows columns={columns} items={rows} onReorder={setRows} />`, primaryProp: { name: "onReorder", type: "(items: SortableDataRow[]) => void", description: "Receives the new row order after drag or keyboard movement." }, accessibility: ["Each row has a labelled reorder handle; Space grabs, arrows move and Space drops.", "Visible up/down buttons provide a touch-safe alternative to desktop drag."], performance: ["Native drag events and discrete reorder updates avoid a pointer-frame React loop."], whenToUse: ["Small to medium tables where order is part of the product model"], whenNotToUse: ["Huge virtualized datasets or touch-only reorder surfaces"], related: ["reorderable-list", "expandable-data-row"] }),
  entry({ component: "ExpandableDataRow", family: "data", slug: "expandable-data-row", name: "Expandable Data Row", description: "A structured row opens its detail surface in place while preserving identity and nearby values.", tags: ["table", "disclosure", "details"], interactions: ["disclosure", "keyboard", "focus"], builtOn: ["AnimatePresence", "stable identity"], usage: `<ExpandableDataRow row={row} columns={["Owner", "Status"]} />`, primaryProp: { name: "row", type: "ExpandableDataRowItem", description: "The row label, values and inline detail content." }, accessibility: ["The complete row is one labelled disclosure button and exposes aria-expanded and a named detail region.", "Detail content remains in the document flow instead of requiring a modal detour."], performance: ["Only the opened detail region mounts; row identity stays stable for quiet updates."], whenToUse: ["Tables that need a focused secondary view without abandoning scan context"], whenNotToUse: ["Dense financial tables where every cell must stay visible at once"], related: ["expandable-list-row", "selection-tray"] }),
  entry({ component: "SelectionTray", family: "data", slug: "selection-tray", name: "Selection Tray", description: "A contextual action tray appears when multiple data items are selected and stays out of the way otherwise.", tags: ["selection", "batch", "actions"], interactions: ["selection", "keyboard", "touch"], builtOn: ["native checkbox", "AnimatePresence"], usage: `<SelectionTray items={items} actions={[{ id: "archive", label: "Archive", onAction: archive }]} />`, primaryProp: { name: "items", type: "SelectionTrayItem[]", description: "Selectable records with a label and optional supporting metadata." }, accessibility: ["Native checkboxes provide an explicit selection path and the tray exposes a named action region.", "Clear and batch actions remain visible and keyboard reachable when selection is active."], performance: ["The tray mounts only with a non-empty selection and actions receive the selected records directly."], whenToUse: ["Batch actions on lists, tables and collection management screens"], whenNotToUse: ["One-off actions that do not benefit from multi-select"], related: ["filter-rail", "reorderable-list"] }),
] satisfies ProductRegistryEntry[];

export const productSystems = { media: mediaSystems, forms: formSystems, data: dataSystems };
export const allProductSystems = [...mediaSystems, ...formSystems, ...dataSystems];
export const getProductSystem = (slug: string) => allProductSystems.find((item) => item.slug === slug);
export function filterProductSystems(family: ProductFamily | "all" = "all", query = "") {
  const needle = query.trim().toLowerCase();
  return allProductSystems.filter((item) => (family === "all" || item.family === family) && (!needle || [item.name, item.description, ...item.tags].join(" ").toLowerCase().includes(needle)));
}
