import type { DiscoveryMetadata, Status } from "./types";

export type WorkflowFamily = "feedback" | "search" | "loading" | "lists" | "drag" | "onboarding" | "mobile";
export type WorkflowEntry = {
  slug: string;
  name: string;
  family: WorkflowFamily;
  description: string;
  status: Status;
  tags: string[];
  component: string;
  builtOn: string[];
  importPath: string;
  usage: string;
  demoPath: string;
  skill: string;
  accessibility: string[];
  reducedMotion: string;
  performance: string[];
  whenToUse: string[];
  whenNotToUse: string[];
  related: string[];
  discovery?: DiscoveryMetadata;
};

const defaults = (item: Omit<WorkflowEntry, "status" | "importPath" | "demoPath" | "skill" | "accessibility" | "reducedMotion" | "performance" | "whenToUse" | "whenNotToUse" | "related"> & Partial<Pick<WorkflowEntry, "accessibility" | "reducedMotion" | "performance" | "whenToUse" | "whenNotToUse" | "related">>): WorkflowEntry => ({
  ...item,
  status: "ready",
  importPath: `import { ${item.component} } from "@pinky/systems";`,
  demoPath: `/workflows#${item.slug}`,
  skill: item.slug,
  accessibility: item.accessibility ?? ["Pointer and keyboard paths expose the same state change.", "Status and focus remain meaningful when motion is disabled."],
  reducedMotion: item.reducedMotion ?? "Resolves state changes without layout animation while preserving semantics.",
  performance: item.performance ?? ["Uses local state and transforms; no per-frame React pointer loop."],
  whenToUse: item.whenToUse ?? ["Product workflows with a clear reversible or inspectable state."],
  whenNotToUse: item.whenNotToUse ?? ["Decorative motion without a user task."],
  related: item.related ?? [],
});

const item = (family: WorkflowFamily, slug: string, name: string, component: string, description: string, tags: string[], usage: string, builtOn: string[] = ["Motion", "native semantics"], discovery?: DiscoveryMetadata) => defaults({ family, slug, name, component, description, tags, usage, builtOn, discovery });

type MobileConfig = Omit<Parameters<typeof defaults>[0], "family">;
const mobileItem = (config: MobileConfig) => defaults({
  family: "mobile",
  accessibility: ["Every gesture has a labelled button or keyboard path, and primary controls meet a 44px touch target.", "State remains readable without relying on colour or motion."],
  reducedMotion: "The same state change resolves immediately; travel, scale and spring motion are removed without removing the interaction.",
  performance: ["Interaction state is local and bounded; gesture updates do not require a page-wide render loop.", "Timers and listeners are cleaned up on unmount."],
  whenToUse: ["Touch-first product surfaces where the next action should stay close to the hand."],
  whenNotToUse: ["Desktop-only workflows or interactions whose gesture would hide the only available action."],
  ...config,
});

export const feedbackSystems = [
  item("feedback", "morph-toast", "Morph Toast", "ToastProvider", "A capped, pausable notification stack with action and swipe dismissal.", ["toast", "notification", "undo"], `<ToastProvider>{children}</ToastProvider>`, ["AnimatePresence", "live regions"]),
  item("feedback", "status-pill", "Status Pill", "StatusPill", "A compact state indicator that carries progress and semantic status.", ["status", "progress", "state"], `<StatusPill label="Uploading" state="working" progress={42} />`),
  item("feedback", "inline-feedback", "Inline Feedback", "InlineFeedback", "Local success, warning, info and error feedback beside the action that caused it.", ["feedback", "validation", "forms"], `<InlineFeedback tone="success">Saved</InlineFeedback>`),
  item("feedback", "action-undo-bar", "Action Undo Bar", "ActionUndoBar", "A temporary recovery surface for reversible actions.", ["undo", "recovery", "action"], `<ActionUndoBar message="Item deleted" onUndo={restore} />`, ["native button", "timer cleanup"], { role: "preset", canonicalSlug: "undoable-action", note: "Use Undoable Action when the removed object must reflow and return to its original position." }),
  item("feedback", "optimistic-action", "Optimistic Action", "OptimisticAction", "Reflects a user action immediately, then confirms it or rolls the visible state back without a fake backend.", ["optimistic", "pending", "rollback", "recovery"], `<OptimisticAction label="Follow" onAction={confirmFollow} />`, ["local state", "aria-pressed"], { role: "canonical", note: "A domain action leads with its likely result while acknowledgement and rollback remain explicit." }),
  item("feedback", "undoable-action", "Undoable Action", "UndoableAction", "Removes an item and closes the gap while a bounded recovery surface restores the exact item position.", ["undo", "reflow", "recovery", "destructive"], `<UndoableAction items={items} onUndo={restore} />`, ["AnimatePresence", "timer cleanup"], { role: "canonical", note: "The recoverable object and its spatial reflow are the interaction, not a toast skin." }),
  item("feedback", "inline-save-state", "Inline Save State", "InlineSaveState", "Keeps edited, saving, saved and failed persistence feedback beside the field that owns the change.", ["save", "persistence", "inline", "retry"], `<InlineSaveState label="Project title" onSave={saveTitle} />`, ["contextual status", "async callback"], { role: "canonical", note: "Persistence feedback stays attached to the edited surface instead of moving to a detached notification." }),
  item("feedback", "async-action-control", "Async Action Control", "AsyncActionControl", "A stable action control that owns pending, success, failure and retry without collapsing into a spinner-only button.", ["async", "action", "success", "failure"], `<AsyncActionControl label="Publish" onAction={publish} />`, ["stable geometry", "async callback"], { role: "canonical", note: "Async Button remains a compact preset; this control makes the complete action lifecycle legible." }),
  item("feedback", "retry-surface", "Retry Surface", "RetrySurface", "Transforms a failed content region into localized recovery with retry and an explicit alternate path.", ["retry", "error", "recovery", "context"], `<RetrySurface title="Preview unavailable" onRetry={reload} />`, ["native button", "local state"], { role: "canonical", note: "Recovery belongs to the surface that failed, so the user keeps context and a next action." }),
  item("feedback", "completion-morph", "Completion Morph", "CompletionMorph", "Transforms a working action surface into its result while preserving spatial ownership and a reset path.", ["completion", "morph", "upload", "continuity"], `<CompletionMorph label="Upload brief" resultLabel="Brief ready" />`, ["Motion layout", "AnimatePresence"], { role: "canonical", note: "The working object becomes the completed object; it does not disappear into a separate success message." }),
  item("feedback", "partial-success-summary", "Partial Success Summary", "PartialSuccessSummary", "Summarizes mixed batch outcomes, preserves successful items and isolates only the failures for retry.", ["batch", "partial", "retry", "summary"], `<PartialSuccessSummary items={results} />`, ["batch state", "retry recovery"], { role: "canonical", note: "A mixed result is neither falsely successful nor needlessly framed as a total failure." }),
  item("feedback", "conflict-resolution", "Conflict Resolution", "ConflictResolution", "Keeps local and external values visible together until the user chooses which version continues.", ["conflict", "compare", "local", "external"], `<ConflictResolution localValue={draft} remoteValue={latest} />`, ["comparison state", "explicit choice"], { role: "canonical", note: "Small, contextual conflict choice without pretending to be a full version-control interface." }),
  item("feedback", "connection-state", "Connection State", "ConnectionState", "Makes offline, reconnecting and restored states actionable while keeping local work available.", ["offline", "reconnect", "sync", "status"], `<ConnectionState defaultMode="offline" onReconnect={reconnect} />`, ["status semantics", "async callback"], { role: "canonical", note: "A product connection state is recoverable and scoped to the work surface, not a browser-style interruption banner." }),
  item("feedback", "delayed-feedback-escalation", "Delayed Feedback Escalation", "DelayedFeedbackEscalation", "Keeps fast actions quiet, then escalates to useful status only when work crosses perceived-performance thresholds.", ["delay", "loading", "perceived performance", "status"], `<DelayedFeedbackEscalation />`, ["threshold timers", "timer cleanup"], { role: "canonical", note: "Avoids flashing a loader for fast work while still telling the truth when an operation takes longer." }),
];
export const searchSystems = [
  item("search", "morph-search", "Morph Search", "MorphSearch", "A compact search trigger expands into an autofocus query surface and restores focus.", ["search", "morph", "focus"], `<MorphSearch query={query} onQueryChange={setQuery} />`, ["Morph", "focus restoration"]),
  item("search", "command-palette", "Command Palette", "CommandPalette", "A reusable keyboard-first command surface with groups, filtering and activation.", ["command", "keyboard", "combobox"], `<CommandPalette items={commands} open={open} onOpenChange={setOpen} />`, ["listbox semantics", "focus restoration"]),
  item("search", "search-results-morph", "Search Results Morph", "SearchResultsMorph", "Stable-identity result transitions with quiet loading and empty states.", ["results", "loading", "filter"], `<SearchResultsMorph items={results} renderItem={renderResult} />`, ["AnimatePresence", "stable keys"]),
];
export const loadingSystems = [
  item("loading", "skeleton-morph", "Skeleton Morph", "SkeletonMorph", "A quiet loading placeholder that resolves into the loaded content geometry.", ["skeleton", "loading", "content"], `<SkeletonMorph loading={loading} skeleton={<CardSkeleton />}>{content}</SkeletonMorph>`),
  item("loading", "shimmer-surface", "Shimmer Surface", "ShimmerSurface", "A restrained material sheen for an active loading surface, with a static reduced-motion fallback.", ["shimmer", "loading", "performance"], `<ShimmerSurface className="h-20 rounded-2xl" />`),
  item("loading", "multi-step-progress", "Multi-Step Progress", "MultiStepProgress", "A visual progress preset for completed, current, upcoming and error states in a staged workflow.", ["progress", "steps", "checkout"], `<MultiStepProgress steps={steps} />`, undefined, { role: "preset", canonicalSlug: "progressive-step-workflow", note: "Use Progressive Step Workflow when completed decisions and the active task need to remain in one product surface." }),
  item("loading", "circular-progress-morph", "Circular Progress Morph", "CircularProgressMorph", "A compact spinner-to-percentage-to-check task indicator.", ["progress", "upload", "status"], `<CircularProgressMorph value={72} state="progress" />`),
  item("loading", "async-button", "Async Button", "AsyncButton", "A width-preserving idle, loading, success and error action pattern.", ["button", "async", "action"], `<AsyncButton onAction={save}>Save changes</AsyncButton>`, ["PressSpring", "stable width"], { role: "preset", canonicalSlug: "async-action-control", note: "Use Async Action Control when the full lifecycle and recovery state need to stay visible." }),
  item("loading", "progressive-status", "Progressive Status", "ProgressiveStatus", "Reveals increasingly specific operational detail only when a single operation takes long enough to need it.", ["status", "processing", "delay", "detail"], `<ProgressiveStatus autoStart steps={steps} />`, ["deterministic timers", "status semantics"], { role: "canonical", note: "The operation starts quiet, then earns detail as elapsed time changes what the user needs to know." }),
  item("loading", "multi-stage-progress", "Multi-Stage Progress", "MultiStageProgress", "Shows system execution moving through named stages with a detailed current stage, failure and retry.", ["progress", "stages", "execution", "retry"], `<MultiStageProgress stages={stages} />`, ["stage state", "responsive layout"], { role: "canonical", note: "This is system execution, not a user-facing wizard; the current stage owns the next operational action." }),
  item("loading", "background-task-row", "Background Task Row", "BackgroundTaskRow", "Keeps a long-running task compact and persistent while the user continues working elsewhere.", ["background", "task", "queued", "progress"], `<BackgroundTaskRow label="Generating preview" />`, ["task state", "progress semantics"], { role: "canonical", note: "A task row preserves status and retry access without blocking the main product surface." }),
  item("loading", "queued-action", "Queued Action", "QueuedAction", "Makes accepted-but-not-yet-started work visible before it enters active processing.", ["queue", "pending", "processing", "position"], `<QueuedAction label="Export report" queuePosition={2} />`, ["queue state", "progress semantics"], { role: "canonical", note: "Queue acceptance is a distinct state from background execution and should not look like an idle button." }),
  item("loading", "resumable-progress", "Resumable Progress", "ResumableProgress", "Preserves progress across an interruption so a long operation can resume instead of restarting.", ["resume", "pause", "long-running", "progress"], `<ResumableProgress label="Importing archive" />`, ["progress state", "resume action"], { role: "canonical", note: "The paused position is part of the product state and remains readable without motion." }),
];
export const listSystems = [
  item("lists", "reorderable-list", "Reorderable List", "ReorderableList", "A controlled list with pointer drag handles, arrow-key moves and announcements.", ["list", "reorder", "keyboard"], `<ReorderableList items={items} onReorder={setItems} />`, ["Motion Reorder", "live region"]),
  item("lists", "expandable-list-row", "Expandable List Row", "ExpandableListRow", "A lightweight list or feed row disclosure for secondary settings, files or task details.", ["list", "disclosure", "details"], `<ExpandableListRow summary="Invoice · #1042">{details}</ExpandableListRow>`, undefined, { role: "solid", note: "Independent list/feed semantics; Expandable Data Row is the structured table pattern." }),
  item("lists", "swipe-action-row", "Swipe Action Row", "SwipeActionRow", "A mobile row that reveals actions while keeping an explicit actions button.", ["swipe", "mobile", "actions"], `<SwipeActionRow actions={actions}>{row}</SwipeActionRow>`, ["touch gesture", "button alternative"]),
  item("lists", "sticky-data-header", "Sticky Data Header", "StickyDataHeader", "A small sticky header surface that preserves list or table context.", ["sticky", "table", "scroll"], `<StickyDataHeader>Project · Owner · Status</StickyDataHeader>`),
  item("lists", "row-spotlight", "Row Spotlight", "RowSpotlight", "A hover and focus state that connects related values without hiding information.", ["table", "focus", "comparison"], `<RowSpotlight><span>Plan · $24 · Active</span></RowSpotlight>`),
];
export const dragSystems = [
  defaults({ family: "drag", slug: "drag-reorder-grid", name: "Drag Reorder Grid", component: "DragReorderGrid", description: "A controlled dashboard grid reordered by keyboard, with native HTML5 mouse dragging as a desktop accelerator.", tags: ["grid", "drag", "dashboard", "keyboard"], usage: `<DragReorderGrid items={widgets} onReorder={setWidgets} />`, builtOn: ["Motion layout", "native HTML5 drag-and-drop", "keyboard movement"],
    accessibility: ["Every item exposes a labelled handle that moves it with the arrow keys.", "Moves are announced through a live region."],
    // Native HTML5 drag-and-drop does not fire on touch. Do not claim touch drag here.
    whenNotToUse: ["Touch-first surfaces — there is no touch drag path; use Reorderable List or Sortable Chips instead."] }),
  item("drag", "drop-indicator", "Drop Indicator", "DropIndicator", "A destination marker that distinguishes insertion from inside-container drops.", ["drop", "insertion", "destination"], `<DropIndicator position="between" active={isOver} />`),
  item("drag", "drag-ghost", "Drag Ghost", "DragGhost", "A restrained preview surface intended to be mounted by a drag integration.", ["drag", "preview", "ghost"], `<DragGhost active={dragging}>{snapshot}</DragGhost>`, ["transform", "drag integration"]),
  item("drag", "sortable-chips", "Sortable Chips", "SortableChips", "A compact tag collection with reorder, remove and add hooks.", ["chips", "tags", "reorder"], `<SortableChips items={tags} onReorder={setTags} onRemove={removeTag} />`),
];
export const onboardingSystems = [
  item("onboarding", "stepper", "Stepper", "Stepper", "A basic horizontal, vertical or compact accessible workflow stepper for explicit progress.", ["steps", "workflow", "progress"], `<Stepper steps={steps} active={active} />`, undefined, { role: "solid", note: "Use Progressive Step Workflow when completed decisions should remain editable context." }),
  item("onboarding", "spotlight-tour", "Spotlight Tour", "SpotlightTour", "A skippable, focus-managed target tour with next, back and Escape paths.", ["tour", "onboarding", "focus"], `<SpotlightTour steps={tourSteps} open={open} onOpenChange={setOpen} />`),
  item("onboarding", "coach-mark", "Coach Mark", "CoachMark", "A single attached teaching surface for a new contextual feature.", ["coach", "teaching", "context"], `<CoachMark target="#new-filter" title="New filters">Try saved views here.</CoachMark>`),
  item("onboarding", "progressive-disclosure", "Progressive Disclosure", "ProgressiveDisclosure", "A small pattern for revealing advanced controls only when requested.", ["disclosure", "settings", "forms"], `<ProgressiveDisclosure>{advancedOptions}</ProgressiveDisclosure>`),
];
export const mobileSystems = [
  item("mobile", "bottom-sheet", "Bottom Sheet", "BottomSheet", "A snap-point sheet with drag, backdrop, Escape and focus restoration.", ["sheet", "mobile", "touch"], `<BottomSheet open={open} onOpenChange={setOpen}>Filters</BottomSheet>`, ["Motion drag", "focus restoration"]),
  item("mobile", "swipeable-tabs", "Swipeable Tabs", "SwipeableTabs", "Fluid Tabs companion with touch swiping and desktop keyboard controls.", ["tabs", "swipe", "mobile"], `<SwipeableTabs tabs={tabs} index={index} onIndexChange={setIndex} />`, ["Fluid Tabs vocabulary", "touch gesture"]),
  item("mobile", "pull-to-refresh", "Pull to Refresh", "PullToRefresh", "A resistance-driven refresh chamber with threshold, armed, refreshing and complete states plus an accessible button path.", ["refresh", "pull", "tension", "mobile"], `<PullToRefresh onRefresh={reload}>{content}</PullToRefresh>`, ["requestAnimationFrame", "pointer capture", "callback-owned data"]),
  item("mobile", "edge-swipe-panel", "Edge Swipe Panel", "EdgeSwipePanel", "A progressive edge reveal that follows the gesture, displaces the underlying surface and settles by distance plus velocity.", ["panel", "edge", "reveal", "gesture"], `<EdgeSwipePanel label="Filters">{filters}</EdgeSwipePanel>`, ["pointer tracking", "velocity settlement", "dialog semantics"]),
  item("mobile", "long-press-action", "Long Press Action", "LongPressAction", "A cancellable long press with click, keyboard and context-menu alternatives.", ["long press", "context", "touch"], `<LongPressAction onLongPress={select}>{item}</LongPressAction>`, ["timer cleanup", "button semantics"]),
  item("mobile", "floating-tab-bar", "Floating Tab Bar", "FloatingTabBar", "A compact mobile navigation bar that lets the active destination expand without losing the surrounding destinations.", ["navigation", "tabs", "active state", "safe area"], `<FloatingTabBar items={items} value={activeId} onValueChange={setActiveId} />`, ["flex morph", "safe-area inset"], { role: "canonical", note: "The canonical compact mobile navigation pattern: active context grows in place while the bar remains reachable." }),
  item("mobile", "contextual-bottom-bar", "Contextual Bottom Bar", "ContextualBottomBar", "Transforms the same bottom region from primary navigation into selection actions while preserving spatial ownership.", ["selection", "navigation", "toolbar", "safe area"], `<ContextualBottomBar selectedCount={selectedCount} onClearSelection={clearSelection} />`, ["AnimatePresence", "toolbar semantics", "safe-area inset"], { role: "canonical", note: "A lower surface changes job when selection changes, instead of adding a second detached toolbar." }),
  item("mobile", "scroll-compact-bottom-nav", "Scroll-Compact Bottom Navigation", "ScrollCompactBottomNav", "Contracts a mobile navigation bar during meaningful downward reading and restores it when the user reverses direction.", ["navigation", "scroll", "compact", "hysteresis"], `<ScrollCompactBottomNav items={items} />`, ["passive scroll listener", "hysteresis"], { role: "canonical", note: "Scroll changes the density of navigation, not its identity; the bar remains discoverable and restores on reversal." }),
  item("mobile", "sticky-bottom-cta", "Sticky Bottom CTA", "StickyBottomCTA", "Keeps the next product action attached to the lower edge with honest pending and disabled states.", ["cta", "sticky", "safe area", "action"], `<StickyBottomCTA label="Continue" description="Ready for the next step" onAction={continueFlow} />`, ["native button", "safe-area inset"], { role: "canonical", note: "A mobile action surface owns the next step without covering the content or relying on a desktop footer." }),
  item("mobile", "floating-action-island", "Floating Action Island", "FloatingActionIsland", "Expands a compact create trigger into local actions and contracts while scrolling without leaving the task context.", ["create", "actions", "floating", "scroll"], `<FloatingActionIsland label="Create" actions={actions} />`, ["AnimatePresence", "passive scroll listener"], { role: "canonical", note: "A local action cluster keeps creation nearby while its closed state stays small enough for mobile browsing." }),
  item("mobile", "swipe-to-confirm", "Swipe to Confirm", "SwipeToConfirm", "Makes a consequential action a bounded horizontal gesture with a keyboard and focus fallback.", ["gesture", "confirm", "touch", "keyboard"], `<SwipeToConfirm label="Archive project" onConfirm={archive} />`, ["pointer capture", "slider semantics"], { role: "canonical", note: "The gesture communicates commitment through distance, while Enter and Space preserve the same action." }),
  item("mobile", "search-morph-header", "Search Morph Header", "SearchMorphHeader", "Morphs a quiet mobile header into an autofocus search field and returns focus to the trigger when closed.", ["search", "header", "morph", "focus"], `<SearchMorphHeader title="Explore" onQueryChange={setQuery} />`, ["AnimatePresence", "focus restoration"], { role: "canonical", note: "Search owns the header region on demand instead of opening a detached desktop-style panel." }),
  item("mobile", "keyboard-aware-composer", "Keyboard-Aware Composer", "KeyboardAwareComposer", "Keeps a composing surface above the visual viewport with a visible send path and safe-area spacing.", ["composer", "keyboard", "safe area", "textarea"], `<KeyboardAwareComposer onSubmit={sendMessage} />`, ["visualViewport", "safe-area inset", "native form"], { role: "canonical", note: "The composer responds to the mobile keyboard as a layout condition, not as a desktop overlay assumption." }),
  item("mobile", "mobile-selection-bar", "Mobile Selection Bar", "MobileSelectionBar", "Turns selected content into a safe-area-aware action bar while leaving each source item individually operable.", ["selection", "batch action", "safe area", "touch"], `<MobileSelectionBar items={items} onAction={moveItems} />`, ["aria-pressed", "safe-area inset"], { role: "canonical", note: "Selection is visible where it happens, and the action tray arrives only after a real item choice." }),
  item("mobile", "progressive-auth-surface", "Progressive Auth Surface", "ProgressiveAuthSurface", "Moves identity, method and verification into one mobile surface so each step stays legible and reversible.", ["auth", "progressive", "verification", "forms"], `<ProgressiveAuthSurface />`, ["native form controls", "aria-live", "one-time-code autocomplete"], { role: "canonical", note: "A mobile auth sequence reveals only the next useful decision while retaining a clear back path." }),
  item("mobile", "auth-completion-morph", "Auth Completion Morph", "AuthCompletionMorph", "Carries a sign-in surface from ready to verifying to complete without replacing the spatial object.", ["auth", "completion", "status", "morph"], `<AuthCompletionMorph />`, ["AnimatePresence", "timer cleanup", "aria-live"], { role: "canonical", note: "Completion stays attached to the action surface so success is readable without a route-sized interruption." }),
  mobileItem({ slug: "morphing-bottom-navigation", name: "Morphing Bottom Navigation", component: "MorphingBottomNavigation", description: "An icon rail gives the active destination a raised labelled surface while the bar keeps a stable thumb-sized footprint.", tags: ["navigation", "bottom", "morph", "touch"], usage: `<MorphingBottomNavigation items={items} value={activeId} onValueChange={setActiveId} />`, builtOn: ["CSS geometry", "native buttons"], discovery: { role: "canonical", note: "Active context changes geometry above a stable mobile rail; it is not only an active colour state." }, related: ["floating-tab-bar", "expandable-bottom-navigation"] }),
  mobileItem({ slug: "floating-dock-navigation", name: "Floating Dock Navigation", component: "FloatingDockNavigation", description: "A resting dock expands the selected destination and keeps one contextual action attached to the same lower surface.", tags: ["navigation", "dock", "context", "touch"], usage: `<FloatingDockNavigation items={items} actionLabel="New" onAction={create} />`, builtOn: ["Motion layout", "safe-area inset"], discovery: { role: "canonical", note: "A product dock with contextual ownership, distinct from a desktop dock imitation or a floating create island." }, related: ["floating-tab-bar", "floating-action-island"] }),
  mobileItem({ slug: "thumb-reach-menu", name: "Thumb-Reach Menu", component: "ThumbReachMenu", description: "A lower trigger fans a short action set upward so important choices stay in the natural reach zone on a large phone.", tags: ["menu", "thumb", "fan", "actions"], usage: `<ThumbReachMenu items={actions} label="More actions" />`, builtOn: ["local menu state", "focus restoration"], discovery: { role: "canonical", note: "Actions rise from the lower edge with a visible menu and Escape path instead of forcing a top-corner trigger." }, related: ["morph-menu", "floating-action-island"] }),
  mobileItem({ slug: "bottom-search-sheet", name: "Bottom Search Sheet", component: "BottomSearchSheet", description: "A compact search pill rises into a keyboard-aware results sheet and returns to the same lower trigger.", tags: ["search", "sheet", "keyboard", "results"], usage: `<BottomSearchSheet results={results} onQueryChange={setQuery} />`, builtOn: ["native input", "focus restoration", "safe-area inset"], discovery: { role: "canonical", note: "Search takes a bottom-sheet path for thumb reach and results continuity; it is not a Command Palette substitute." }, related: ["search-morph-header", "command-palette"] }),
  mobileItem({ slug: "search-filter-morph", name: "Search + Filter Morph", component: "SearchFilterMorph", description: "Search and filter chips emerge from one compact surface so refinement does not break the current reading context.", tags: ["search", "filters", "chips", "morph"], usage: `<SearchFilterMorph filters={filters} query={query} onQueryChange={setQuery} />`, builtOn: ["native input", "pressed buttons"], discovery: { role: "canonical", note: "The query and filter states share one mobile surface instead of becoming two disconnected controls." }, related: ["filter-rail", "search-morph-header"] }),
  mobileItem({ slug: "inline-search-reveal", name: "Inline Search Reveal", component: "InlineSearchReveal", description: "A search icon reflows the local header into an inline field without reserving a permanent desktop search row.", tags: ["search", "inline", "reflow", "focus"], usage: `<InlineSearchReveal title="Saved notes" onQueryChange={setQuery} />`, builtOn: ["CSS reflow", "focus restoration"], discovery: { role: "canonical", note: "The field enters the content header itself, pushing nearby content rather than opening a viewport overlay." }, related: ["search-morph-header", "expanding-search"] }),
  mobileItem({ slug: "detent-sheet", name: "Detent Sheet", component: "DetentSheet", description: "A sheet exposes peek, half and full heights as stable destinations with drag, buttons and keyboard controls.", tags: ["sheet", "detent", "drag", "mobile"], usage: `<DetentSheet open={open} onOpenChange={setOpen} title="Filters" />`, builtOn: ["Motion drag", "focus restoration", "safe-area inset"], discovery: { role: "canonical", note: "Three named detents make drag handoff predictable; this is a stable height system, not another generic bottom sheet." }, related: ["bottom-sheet", "content-aware-sheet"] }),
  mobileItem({ slug: "content-aware-sheet", name: "Content-Aware Sheet", component: "ContentAwareSheet", description: "A local sheet grows with the content it reveals and stops at a bounded viewport height instead of forcing a fixed 80vh shell.", tags: ["sheet", "content", "resize", "disclosure"], usage: `<ContentAwareSheet title="Details" expandedContent={more}>{summary}</ContentAwareSheet>`, builtOn: ["natural flow", "Motion layout"], discovery: { role: "canonical", note: "Height follows content density while the surface remains bounded and scrollable when needed." }, related: ["detent-sheet", "bottom-sheet"] }),
  mobileItem({ slug: "swipe-dismiss-card-sheet", name: "Swipe-to-Dismiss Card Sheet", component: "SwipeDismissCardSheet", description: "A card sheet follows vertical drag with translation, scale and scrim response before snapping back or dismissing.", tags: ["sheet", "swipe", "card", "dismiss"], usage: `<SwipeDismissCardSheet open={open} onOpenChange={setOpen} title="Preview" />`, builtOn: ["pointer capture", "transform response"], discovery: { role: "canonical", note: "The card itself communicates release through coordinated travel and scale, with a close button and Escape fallback." }, related: ["bottom-sheet", "morph-lightbox"] }),
  mobileItem({ slug: "long-press-selection", name: "Long-Press Selection", component: "LongPressSelection", description: "Long press enters batch selection with tactile-ready state language, while tap, check buttons and keyboard remain complete paths.", tags: ["selection", "long press", "batch", "touch"], usage: `<LongPressSelection items={items} onAction={moveItems} />`, builtOn: ["press timer", "aria-pressed", "safe-area inset"], discovery: { role: "canonical", note: "Selection is a mode change with a lower action tray, not a hidden hover affordance." }, related: ["long-press-action", "mobile-selection-bar", "selection-tray"] }),
  mobileItem({ slug: "swipe-actions", name: "Swipe Actions", component: "SwipeActions", description: "A row reveals an action at a snap threshold and commits only after a farther threshold, with a visible button alternative.", tags: ["swipe", "row", "threshold", "actions"], usage: `<SwipeActions label="Archive project" actionLabel="Archive" onAction={archive} />`, builtOn: ["pointer capture", "threshold state"], discovery: { role: "canonical", note: "Reveal and commit are separate distances, so a partial swipe can be cancelled instead of accidentally firing." }, related: ["swipe-action-row", "swipe-to-confirm"] }),
  mobileItem({ slug: "focus-lift-field", name: "Focus Lift Field", component: "FocusLiftField", description: "A focused field lifts its local surface and reveals helper context without letting the mobile keyboard erase the field relationship.", tags: ["forms", "focus", "field", "mobile"], usage: `<FocusLiftField label="Workspace name" description="Shown to collaborators." />`, builtOn: ["native input", "focus state"], discovery: { role: "canonical", note: "Focus changes local geometry and supporting copy, not just a border colour." }, related: ["validation-field", "keyboard-aware-composer"] }),
  mobileItem({ slug: "mobile-validation-morph", name: "Mobile Validation Morph", component: "MobileValidationMorph", description: "Inline validation changes the field surface, status marker and message together while keeping correction in place.", tags: ["forms", "validation", "status", "mobile"], usage: `<MobileValidationMorph label="Email" defaultValue="" />`, builtOn: ["native input", "aria-invalid", "status region"], discovery: { role: "canonical", note: "The status is readable through icon, message and surface structure; colour is never the only signal." }, related: ["validation-field", "inline-feedback"] }),
  mobileItem({ slug: "progressive-mobile-form", name: "Progressive Mobile Form", component: "ProgressiveMobileForm", description: "Completed groups compress into editable summaries while the current group stays open and the next group is previewed.", tags: ["forms", "progressive", "steps", "mobile"], usage: `<ProgressiveMobileForm steps={steps} />`, builtOn: ["controlled form state", "native inputs"], discovery: { role: "canonical", note: "A mobile form keeps one decision open at a time without hiding completed answers." }, related: ["progressive-form", "progressive-step-workflow"] }),
  mobileItem({ slug: "card-stack-browse", name: "Card Stack Browse", component: "CardStackBrowse", description: "A small editorial card stack uses bounded drag distance to let the next card gain depth without becoming a swipe-to-dismiss clone.", tags: ["cards", "stack", "drag", "browse"], usage: `<CardStackBrowse items={items} />`, builtOn: ["pointer capture", "layered surfaces"], discovery: { role: "canonical", note: "The stack is for sequential browsing and keeps a next-card relationship visible, not for binary accept/reject gestures." }, related: ["draggable-card-stack", "focus-rail-mobile"] }),
  mobileItem({ slug: "expand-in-place-card", name: "Expand-in-Place Card", component: "ExpandInPlaceCard", description: "A compact card expands inside the same document flow so content below reflows around the selected source.", tags: ["cards", "expand", "reflow", "mobile"], usage: `<ExpandInPlaceCard items={items} />`, builtOn: ["Motion layout", "aria-expanded"], discovery: { role: "canonical", note: "The selected object remains the reading anchor; this is not a modal or a hidden detail route." }, related: ["expandable-content-row", "morph-card"] }),
  mobileItem({ slug: "focus-rail-mobile", name: "Focus Rail Mobile", component: "FocusRailMobile", description: "A native horizontal rail keeps neighboring items visible while the centered item gains scale and reading priority.", tags: ["rail", "scroll-snap", "collection", "mobile"], usage: `<FocusRailMobile items={items} />`, builtOn: ["CSS scroll snap", "native horizontal scroll"], discovery: { role: "canonical", note: "The rail uses native scrolling as the gesture and makes focus visible through scale, opacity and centered context." }, related: ["focus-rail", "horizontal-peek-rail"] }),
  mobileItem({ slug: "fullscreen-media-morph", name: "Fullscreen Media Morph", component: "FullscreenMediaMorph", description: "A thumbnail grows into a focused media surface and returns to its source with focus and identity preserved.", tags: ["media", "fullscreen", "morph", "touch"], usage: `<FullscreenMediaMorph items={media} />`, builtOn: ["dialog semantics", "focus restoration"], discovery: { role: "canonical", note: "Fullscreen is a continuation of the tapped media object, not an unrelated gallery shell or hardware mockup." }, related: ["morph-lightbox", "expandable-media"] }),
  mobileItem({ slug: "swipe-media-inspector", name: "Swipe Media Inspector", component: "SwipeMediaInspector", description: "An open media surface reveals metadata on upward swipe while keeping an explicit Details control and downward return.", tags: ["media", "inspector", "swipe", "metadata"], usage: `<SwipeMediaInspector title="Working room" />`, builtOn: ["vertical gesture", "attached panel"], discovery: { role: "canonical", note: "Metadata moves with the media reading surface instead of opening a fixed detached overlay." }, related: ["fullscreen-media-morph", "anchored-inspector"] }),
  mobileItem({ slug: "floating-media-controls", name: "Floating Media Controls", component: "FloatingMediaControls", description: "Media controls stay minimal at rest, reveal on tap and collapse after idle without hiding the primary play path.", tags: ["media", "controls", "idle", "touch"], usage: `<FloatingMediaControls label="Lesson 01" />`, builtOn: ["native button", "timer cleanup"], discovery: { role: "canonical", note: "The control layer responds to touch intent and does not depend on hover to expose playback." }, related: ["floating-media-player", "expandable-media"] }),
  mobileItem({ slug: "bottom-toast-stack", name: "Bottom Toast Stack", component: "BottomToastStack", description: "Short messages stack and compress at the lower edge, where mobile feedback is easier to reach and read.", tags: ["feedback", "toast", "stack", "safe area"], usage: `<BottomToastStack />`, builtOn: ["live region", "timer cleanup", "safe-area inset"], discovery: { role: "canonical", note: "A mobile bottom stack is a distinct placement and density system, not a desktop corner toast moved downward." }, related: ["morph-toast", "action-undo-bar"] }),
  mobileItem({ slug: "mobile-undo-bar", name: "Mobile Undo Bar", component: "MobileUndoBar", description: "A reversible action closes its gap and exposes a thumb-reachable undo surface that restores the exact item.", tags: ["feedback", "undo", "reflow", "mobile"], usage: `<MobileUndoBar />`, builtOn: ["local list state", "timer cleanup", "safe-area inset"], discovery: { role: "canonical", note: "The recovery surface belongs to the reflowing list and keeps the removed object recoverable." }, related: ["action-undo-bar", "undoable-action"] }),
  mobileItem({ slug: "quick-action-sheet", name: "Quick Action Sheet", component: "QuickActionSheet", description: "A searchable action sheet combines recent and contextual actions so mobile command entry does not depend on a desktop shortcut.", tags: ["actions", "search", "sheet", "mobile"], usage: `<QuickActionSheet actions={actions} />`, builtOn: ["native input", "focus restoration", "safe-area inset"], discovery: { role: "canonical", note: "A mobile command equivalent keeps action search close to the thumb while retaining semantic buttons and Escape." }, related: ["command-palette", "bottom-search-sheet"] }),
  mobileItem({ slug: "hold-to-reveal-actions", name: "Hold-to-Reveal Actions", component: "HoldToRevealActions", description: "Holding a primary action reveals secondary choices in place, with a visible Cancel state and keyboard fallback.", tags: ["long press", "actions", "reveal", "touch"], usage: `<HoldToRevealActions label="Publish" actions={actions} />`, builtOn: ["press timer", "native buttons"], discovery: { role: "canonical", note: "Secondary actions are revealed by sustained intent but remain cancellable and available through keyboard activation." }, related: ["long-press-action", "thumb-reach-menu"] }),
];

export const productWorkflowSystems = [
  defaults({ family: "onboarding", slug: "progressive-step-workflow", name: "Progressive Step Workflow", component: "ProgressiveStepWorkflow", description: "A staged product workflow keeps completed decisions compact, the active decision large and the next context visible.", tags: ["workflow", "steps", "progressive"], usage: `<ProgressiveStepWorkflow steps={steps} onActiveIdChange={setActive} />`, builtOn: ["controlled state", "Motion layout"], accessibility: ["The current task uses aria-current while completed decisions remain explicit edit buttons.", "Continue, Back and blocked states use text labels, and state changes are announced only after an action."], reducedMotion: "Removes layout travel while completed, current, blocked and upcoming structure stays visible.", performance: ["Only the current task content renders; updates are discrete and host controlled."], whenToUse: ["Short product workflows where completed decisions should remain editable context."], whenNotToUse: ["Long branching processes that need routing, persistence or a dedicated review screen."], related: ["stepper", "progressive-disclosure"], discovery: { role: "canonical", note: "Canonical product workflow for progressive decision continuity." } }),
  defaults({ family: "feedback", slug: "status-pipeline", name: "Status Pipeline", component: "StatusPipeline", description: "A queued-to-active-to-complete status path keeps failure and retry on the same spatial track.", tags: ["status", "pipeline", "progress"], usage: `<StatusPipeline stages={stages} failedId={failedId} onRetry={retry} />`, builtOn: ["Motion layout", "semantic state"], accessibility: ["Every stage exposes its named state and the current stage uses aria-current.", "Failure, retry and completion are written as text as well as shown through color and symbols."], reducedMotion: "Keeps the complete status track and swaps state immediately without animated travel.", performance: ["A small fixed stage list updates on explicit actions without timers or continuous work."], whenToUse: ["Operational flows where queued, active, failed and completed states need spatial continuity."], whenNotToUse: ["A single indeterminate task or decorative percentage meter."], related: ["multi-step-progress", "status-pill"] }),
];

export const workflowSystems = [...feedbackSystems, ...searchSystems, ...loadingSystems, ...listSystems, ...dragSystems, ...onboardingSystems, ...mobileSystems, ...productWorkflowSystems] satisfies WorkflowEntry[];
export const allWorkflowSystems = workflowSystems;
export function getWorkflowSystem(slug: string) { return allWorkflowSystems.find((entry) => entry.slug === slug); }
export function filterWorkflowSystems(family: WorkflowFamily | "all" = "all", query = "") { const needle = query.trim().toLowerCase(); return allWorkflowSystems.filter((entry) => (family === "all" || entry.family === family) && (!needle || [entry.name, entry.description, ...entry.tags].join(" ").toLowerCase().includes(needle))); }
