"use client";

import { AnimatePresence, motion } from "motion/react";
import { useMotionEnabled } from "@pinky/primitives";
import { useCallback, useEffect, useId, useRef, useState, type ReactNode } from "react";
import { cn } from "../internal/cn";

export type StepState = "completed" | "current" | "upcoming" | "error";
export type StepItem = { id: string; label: string; description?: string; state?: StepState };
export function Stepper({ steps, active, defaultActive = 0, onActiveChange, orientation = "horizontal", compact = false, allowNavigation = false, label = "Steps", className }: { steps: StepItem[]; active?: number; defaultActive?: number; onActiveChange?: (index: number) => void; orientation?: "horizontal" | "vertical"; compact?: boolean; allowNavigation?: boolean; label?: string; className?: string }) {
  const [internal, setInternal] = useState(defaultActive); const current = active ?? internal; const set = (index: number) => { if (active === undefined) setInternal(index); onActiveChange?.(index); };
  return <ol aria-label={label} className={cn("flex gap-3", orientation === "vertical" ? "flex-col" : "items-start", className)}>{steps.map((step, index) => <li key={step.id} className={cn("flex min-w-0 flex-1 gap-2", orientation === "vertical" ? "items-start" : "items-center")} aria-current={index === current ? "step" : undefined}>{allowNavigation ? <button type="button" onClick={() => set(index)} aria-label={`${index + 1}. ${step.label}`} className="grid size-8 shrink-0 place-items-center rounded-full border focus-visible:ring-2">{step.state === "completed" || index < current ? "✓" : index + 1}</button> : <span aria-hidden className="grid size-8 shrink-0 place-items-center rounded-full border">{step.state === "completed" || index < current ? "✓" : index + 1}</span>}<span className={cn("min-w-0", compact && "sr-only")}><span className="block truncate text-sm font-medium">{step.label}</span>{!compact && step.description ? <span className="mt-1 block text-xs text-ink-500">{step.description}</span> : null}</span></li>)}</ol>;
}

export type TourStep = { id: string; target?: string; title: string; description: ReactNode };
export function SpotlightTour({ steps, open, defaultOpen = false, onOpenChange, step, defaultStep = 0, onStepChange, label = "Product tour" }: { steps: TourStep[]; open?: boolean; defaultOpen?: boolean; onOpenChange?: (open: boolean) => void; step?: number; defaultStep?: number; onStepChange?: (step: number) => void; label?: string }) {
  const [shownInternal, setShownInternal] = useState(defaultOpen); const [stepInternal, setStepInternal] = useState(defaultStep); const shown = open ?? shownInternal; const current = step ?? stepInternal; const [rect, setRect] = useState<DOMRect | null>(null); const dialog = useRef<HTMLDivElement>(null); const motionEnabled = useMotionEnabled(); const setShown = useCallback((value: boolean) => { if (open === undefined) setShownInternal(value); onOpenChange?.(value); }, [onOpenChange, open]); const setCurrent = useCallback((value: number) => { if (step === undefined) setStepInternal(value); onStepChange?.(value); }, [onStepChange, step]);
  useEffect(() => { if (!shown) return; const target = steps[current]?.target ? document.querySelector<HTMLElement>(steps[current].target!) : null; target?.scrollIntoView({ block: "center", behavior: motionEnabled ? "smooth" : "auto" }); const update = () => setRect(target?.getBoundingClientRect() ?? null); update(); window.addEventListener("resize", update); dialog.current?.focus(); return () => window.removeEventListener("resize", update); }, [current, motionEnabled, shown, steps]);
  useEffect(() => { if (!shown) return; const onKey = (event: globalThis.KeyboardEvent) => { if (event.key === "Escape") setShown(false); }; document.addEventListener("keydown", onKey); return () => document.removeEventListener("keydown", onKey); }, [setShown, shown]);
  const item = steps[current]; if (!item) return null; const spotlightStyle = rect ? { top: Math.max(8, rect.top - 8), left: Math.max(8, rect.left - 8), width: rect.width + 16, height: rect.height + 16 } : undefined;
  return <AnimatePresence>{shown ? <motion.div role="presentation" className="fixed inset-0 z-[85]" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><div className="absolute inset-0 bg-ink-900/55" />{rect ? <div aria-hidden className="pointer-events-none absolute rounded-2xl ring-4 ring-white/90 ring-offset-4 ring-offset-transparent" style={spotlightStyle} /> : null}<motion.div ref={dialog} tabIndex={-1} role="dialog" aria-modal="true" aria-label={label} className="absolute right-4 bottom-4 left-4 mx-auto max-w-md rounded-[24px] bg-white p-5 shadow-2xl sm:right-8 sm:bottom-8 sm:left-auto" initial={motionEnabled ? { y: 12, opacity: 0 } : false} animate={{ y: 0, opacity: 1 }}><p className="font-mono text-xs text-ink-500">{current + 1} / {steps.length}</p><h2 className="mt-2 text-xl font-semibold">{item.title}</h2><div className="mt-2 text-sm leading-relaxed text-ink-700">{item.description}</div><div className="mt-5 flex items-center justify-between gap-3"><button type="button" onClick={() => setShown(false)} className="text-sm text-ink-500">Skip tour</button><div className="flex gap-2"><button type="button" disabled={current === 0} onClick={() => setCurrent(current - 1)} className="rounded-full border border-line px-3 py-2 text-sm">Back</button><button type="button" onClick={() => current === steps.length - 1 ? setShown(false) : setCurrent(current + 1)} className="rounded-full bg-ink-900 px-4 py-2 text-sm text-milk">{current === steps.length - 1 ? "Done" : "Next"}</button></div></div></motion.div></motion.div> : null}</AnimatePresence>;
}

export function CoachMark({ target, title, children, open = true, onDismiss, placement = "bottom", className }: { target?: string; title: string; children: ReactNode; open?: boolean; onDismiss?: () => void; placement?: "top" | "bottom" | "left" | "right"; className?: string }) { const [rect, setRect] = useState<DOMRect | null>(null); useEffect(() => { const node = target ? document.querySelector<HTMLElement>(target) : null; const update = () => setRect(node?.getBoundingClientRect() ?? null); update(); window.addEventListener("resize", update); return () => window.removeEventListener("resize", update); }, [target]); if (!open) return null; const style = rect ? { top: placement === "bottom" ? rect.bottom + 10 : placement === "top" ? rect.top - 10 : rect.top, left: placement === "right" ? rect.right + 10 : placement === "left" ? rect.left - 10 : rect.left } : undefined; return <div role="status" className={cn("fixed z-[75] max-w-xs rounded-2xl border border-line bg-white p-4 shadow-xl", className)} style={style}><div className="flex gap-3"><div className="flex-1"><h2 className="font-medium">{title}</h2><div className="mt-1 text-sm text-ink-700">{children}</div></div>{onDismiss ? <button type="button" onClick={onDismiss} aria-label="Dismiss tip">×</button> : null}</div></div>; }
export function ProgressiveDisclosure({ label = "Show advanced", children, defaultOpen = false, open, onOpenChange, className }: { label?: string; children: ReactNode; defaultOpen?: boolean; open?: boolean; onOpenChange?: (open: boolean) => void; className?: string }) { const [internal, setInternal] = useState(defaultOpen); const shown = open ?? internal; const set = (value: boolean) => { if (open === undefined) setInternal(value); onOpenChange?.(value); }; const id = useId(); return <div className={className}><button type="button" aria-expanded={shown} aria-controls={shown ? id : undefined} onClick={() => set(!shown)} className="rounded-full border border-line px-4 py-2 text-sm">{shown ? "Hide advanced" : label}</button><AnimatePresence initial={false}>{shown ? <motion.div id={id} initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden"><div className="pt-4">{children}</div></motion.div> : null}</AnimatePresence></div>; }
