"use client";

import { AnimatePresence, LayoutGroup, motion } from "motion/react";
import { useMotionEnabled } from "@pinky/primitives";
import { useEffect, useId, useMemo, useRef, useState, type KeyboardEvent, type ReactNode } from "react";
import { cn } from "../internal/cn";
import { useControllable } from "../internal/use-controllable";

export function MorphSearch({ query, defaultQuery = "", onQueryChange, label = "Search", placeholder = "Search…", results, className }: { query?: string; defaultQuery?: string; onQueryChange?: (value: string) => void; label?: string; placeholder?: string; results?: ReactNode; className?: string }) {
  const [value, setValue] = useControllable(query, defaultQuery, onQueryChange); const [open, setOpen] = useState(false); const input = useRef<HTMLInputElement>(null); const trigger = useRef<HTMLButtonElement>(null); const motionEnabled = useMotionEnabled();
  useEffect(() => { if (open) input.current?.focus(); }, [open]); const close = () => { setOpen(false); requestAnimationFrame(() => trigger.current?.focus()); };
  return <LayoutGroup>{open ? <motion.div layoutId="morph-search" className={cn("rounded-2xl border border-line bg-white p-3 shadow-xl", className)}><label className="flex items-center gap-2"><span className="sr-only">{label}</span><span aria-hidden>⌕</span><input ref={input} type="search" value={value} onChange={(event) => setValue(event.currentTarget.value)} onKeyDown={(event) => { if (event.key === "Escape") close(); }} placeholder={placeholder} className="min-w-0 flex-1 bg-transparent outline-none" />{value ? <button type="button" onClick={() => { setValue(""); input.current?.focus(); }} aria-label="Clear search">×</button> : null}<button type="button" onClick={close} aria-label="Close search">Close</button></label>{results ? <div className="mt-3 border-t border-line pt-3">{results}</div> : null}</motion.div> : <motion.button ref={trigger} layoutId="morph-search" type="button" onClick={() => setOpen(true)} className={cn("rounded-full border border-line bg-white px-4 py-2 shadow-sm", className)} transition={motionEnabled ? { type: "spring", stiffness: 340, damping: 32 } : { duration: 0 }} aria-label={label}>⌕ <span className="ml-2">{label}</span></motion.button>}</LayoutGroup>;
}

export type CommandItem = { id: string; label: string; group?: string; keywords?: string[]; onSelect: () => void; disabled?: boolean };
export function CommandPalette({ items, open, defaultOpen = false, onOpenChange, label = "Command palette", empty = "No commands found", recentIds = [] }: { items: CommandItem[]; open?: boolean; defaultOpen?: boolean; onOpenChange?: (open: boolean) => void; label?: string; empty?: ReactNode; recentIds?: string[] }) {
  const [shown, setShown] = useControllable(open, defaultOpen, onOpenChange); const [query, setQuery] = useState(""); const [active, setActive] = useState(0); const input = useRef<HTMLInputElement>(null); const dialog = useRef<HTMLDivElement>(null); const previous = useRef<HTMLElement | null>(null); const id = useId();
  const filtered = useMemo(() => items.filter((item) => !item.disabled && [item.label, ...(item.keywords ?? [])].join(" ").toLowerCase().includes(query.toLowerCase())).sort((a, b) => Number(recentIds.includes(b.id)) - Number(recentIds.includes(a.id))), [items, query, recentIds]);
  useEffect(() => { if (!shown) return; previous.current = document.activeElement as HTMLElement; input.current?.focus(); const key = (event: globalThis.KeyboardEvent) => { if (event.key === "Escape") setShown(false); }; document.addEventListener("keydown", key); return () => { document.removeEventListener("keydown", key); previous.current?.focus(); }; }, [setShown, shown]);
  useEffect(() => setActive(0), [query]);
  const keys = (event: KeyboardEvent) => { if (event.key === "ArrowDown" || event.key === "ArrowUp") { event.preventDefault(); setActive((value) => (value + (event.key === "ArrowDown" ? 1 : -1) + filtered.length) % Math.max(filtered.length, 1)); } if (event.key === "Enter") { event.preventDefault(); filtered[active]?.onSelect(); if (filtered[active]) setShown(false); } };
  const trap = (event: KeyboardEvent) => { if (event.key !== "Tab") return; const focusable = [input.current, ...Array.from(dialog.current?.querySelectorAll<HTMLButtonElement>("button:not([disabled])") ?? [])].filter((node): node is HTMLButtonElement | HTMLInputElement => node !== null); const first = focusable[0]; const last = focusable.at(-1); if (!first || !last) return; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } };
  return <AnimatePresence>{shown ? <motion.div role="presentation" className="fixed inset-0 z-[90] grid place-items-start bg-ink-900/30 p-4 pt-[12vh]" onMouseDown={(event) => { if (event.target === event.currentTarget) setShown(false); }} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><motion.div ref={dialog} role="dialog" aria-modal="true" aria-label={label} onKeyDown={trap} className="mx-auto w-full max-w-xl rounded-[24px] bg-white p-3 shadow-2xl" initial={{ y: -10, scale: .98 }} animate={{ y: 0, scale: 1 }}><label className="flex items-center gap-3 border-b border-line px-3 py-3"><span aria-hidden>⌘</span><span className="sr-only">Search commands</span><input ref={input} role="combobox" aria-controls={id} aria-expanded="true" aria-activedescendant={filtered[active] ? `${id}-${filtered[active].id}` : undefined} value={query} onChange={(event) => setQuery(event.currentTarget.value)} onKeyDown={keys} placeholder="Type a command…" className="flex-1 outline-none" /></label><div id={id} role="listbox" className="max-h-80 overflow-auto p-1">{filtered.map((item, index) => <button id={`${id}-${item.id}`} key={item.id} type="button" role="option" aria-selected={index === active} onMouseMove={() => setActive(index)} onClick={() => { item.onSelect(); setShown(false); }} className={cn("flex w-full justify-between rounded-xl px-3 py-2.5 text-left", index === active && "bg-blush-50")}><span>{item.label}</span>{item.group ? <span className="text-xs text-ink-500">{item.group}</span> : null}</button>)}{!filtered.length ? <div className="p-6 text-center text-ink-500">{empty}</div> : null}</div></motion.div></motion.div> : null}</AnimatePresence>;
}

export function useCommandShortcut(callback: () => void, key = "k") { const current = useRef(callback); current.current = callback; useEffect(() => { const handler = (event: globalThis.KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === key.toLowerCase()) { event.preventDefault(); current.current(); } }; document.addEventListener("keydown", handler); return () => document.removeEventListener("keydown", handler); }, [key]); }
export function SearchResultsMorph<T extends { id: string }>({ items, renderItem, loading = false, empty = "No results", className }: { items: T[]; renderItem: (item: T) => ReactNode; loading?: boolean; empty?: ReactNode; className?: string }) { const enabled = useMotionEnabled(); return <div aria-busy={loading} aria-live="polite" className={className}>{loading ? <p role="status" className="p-4 text-sm text-ink-500">Searching…</p> : !items.length ? <p className="p-4 text-sm text-ink-500">{empty}</p> : <motion.ul layout={enabled} className="space-y-2"><AnimatePresence initial={false}>{items.map((item) => <motion.li layout={enabled} key={item.id} initial={enabled ? { opacity: 0, y: 4 } : false} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}>{renderItem(item)}</motion.li>)}</AnimatePresence></motion.ul>}</div>; }
