import type { Metadata } from "next";
import Link from "next/link";
import { allProductSystems } from "@pinky/registry";

import { ProductSystemsExpansion } from "@/components/systems/product-expansion-showcase";
import { DataVisualizationShowcase } from "@/components/systems/data-visualization-showcase";
import { OverlaysShowcase } from "@/components/systems/overlays-showcase";
import { RegistryCatalogue } from "@/components/site/registry-catalogue";

export const metadata: Metadata = { title: "Systems", description: "Product forms, data, overlays, collections and workflow patterns for real interfaces." };

export default function SystemsPage() {
  return <main className="pb-32"><header className="border-b border-line bg-[linear-gradient(135deg,var(--color-blush-50),var(--color-cloud-50))]"><div className="mx-auto max-w-[76rem] px-5 py-12 sm:px-8 sm:py-16"><p className="font-mono text-[0.6875rem] tracking-[0.18em] text-ink-500 uppercase">Product systems · contextual layer</p><h1 className="mt-4 max-w-3xl text-section text-balance-tight">Real product structure, with a little more feeling.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-ink-700">Forms, data, overlays and workflows that preserve context, native semantics and a clear next action.</p><nav aria-label="System families" className="mt-8 flex flex-wrap gap-2"><Link href="/forms" className="rounded-full border border-line bg-white/70 px-3 py-2 text-sm">All forms</Link><Link href="/collections" className="rounded-full border border-line bg-white/70 px-3 py-2 text-sm">Collections</Link><Link href="/data" className="rounded-full border border-line bg-white/70 px-3 py-2 text-sm">All data</Link><Link href="/workflows" className="rounded-full border border-line bg-white/70 px-3 py-2 text-sm">All workflows</Link><Link href="/overlays" className="rounded-full border border-line bg-white/70 px-3 py-2 text-sm">All overlays</Link><Link href="#browse-all" className="rounded-full border border-line bg-white/70 px-3 py-2 text-sm">Browse all {allProductSystems.length}</Link><Link href="/explore" className="rounded-full bg-ink-900 px-3 py-2 text-sm text-milk">Explore registry</Link></nav></div></header><section className="mx-auto max-w-[76rem] px-5 pt-20 sm:px-8"><p className="font-mono text-[0.6875rem] tracking-[0.18em] text-ink-500 uppercase">01 · Forms</p><h2 className="mt-4 max-w-2xl text-section text-balance-tight">Fields that keep their context.</h2><ProductSystemsExpansion family="forms" /></section><section className="mx-auto max-w-[76rem] px-5 pt-24 sm:px-8"><p className="font-mono text-[0.6875rem] tracking-[0.18em] text-ink-500 uppercase">02 · Data</p><h2 className="mt-4 max-w-2xl text-section text-balance-tight">Rows that remain useful while they move.</h2><ProductSystemsExpansion family="data" /><DataVisualizationShowcase compact /></section><section className="mx-auto max-w-[76rem] px-5 pt-24 sm:px-8"><p className="font-mono text-[0.6875rem] tracking-[0.18em] text-ink-500 uppercase">03 · Workflows</p><h2 className="mt-4 max-w-2xl text-section text-balance-tight">Progress that keeps its product context.</h2><ProductSystemsExpansion family="workflows" /></section><section className="mx-auto max-w-[76rem] px-5 pt-24 sm:px-8"><p className="font-mono text-[0.6875rem] tracking-[0.18em] text-ink-500 uppercase">04 · Overlays</p><h2 className="mt-4 max-w-2xl text-section text-balance-tight">Context that stays close to its source.</h2><OverlaysShowcase compact /></section><RegistryCatalogue id="browse-all" items={allProductSystems} hrefPrefix="/systems" label="systems" /></main>;
}
