"use client";

import { AnimatePresence, motion } from "motion/react";
import { useMotionEnabled } from "@pinky/primitives";
import { useEffect, useId, useRef, useState, type PointerEvent as ReactPointerEvent, type ReactNode } from "react";
import { cn } from "../internal/cn";
import { useControllable } from "../internal/use-controllable";

export function BottomSheet({ open, defaultOpen = false, onOpenChange, snapPoints = [45, 85], title = "Sheet", children, className }: { open?: boolean; defaultOpen?: boolean; onOpenChange?: (open: boolean) => void; snapPoints?: number[]; title?: string; children: ReactNode; className?: string }) { const [shown, setShown] = useControllable(open, defaultOpen, onOpenChange); const [snap, setSnap] = useState(0); const previous = useRef<HTMLElement | null>(null); const sheet = useRef<HTMLElement>(null); const titleId = useId(); const enabled = useMotionEnabled(); useEffect(() => { if (!shown) return; previous.current = document.activeElement as HTMLElement; sheet.current?.focus(); const key = (event: globalThis.KeyboardEvent) => { if (event.key === "Escape") setShown(false); }; document.addEventListener("keydown", key); return () => { document.removeEventListener("keydown", key); previous.current?.focus(); }; }, [setShown, shown]); return <AnimatePresence>{shown ? <motion.div className="fixed inset-0 z-[80] flex items-end bg-ink-900/35" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={(event) => { if (event.target === event.currentTarget) setShown(false); }}><motion.section ref={sheet} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby={titleId} drag={enabled ? "y" : false} dragConstraints={{ top: 0, bottom: 0 }} dragElastic={.18} onDragEnd={(_, info) => { if (info.offset.y > 100) setShown(false); else if (info.offset.y < -70) setSnap(Math.min(snap + 1, snapPoints.length - 1)); }} initial={{ y: "100%" }} animate={{ y: 0, height: `${snapPoints[snap] ?? 45}vh` }} exit={{ y: "100%" }} className={cn("w-full overflow-y-auto rounded-t-[28px] bg-white p-5 shadow-2xl", className)}><div className="mx-auto mb-4 h-1.5 w-12 rounded-full bg-cloud-200" /><div className="flex items-center justify-between"><h2 id={titleId} className="text-lg font-semibold">{title}</h2><button type="button" aria-label="Close sheet" onClick={() => setShown(false)} className="rounded-full p-2">×</button></div><div className="mt-5">{children}</div></motion.section></motion.div> : null}</AnimatePresence>; }

export type SwipeTab = { id: string; label: string; panel: ReactNode };
export function SwipeableTabs({ tabs, index, defaultIndex = 0, onIndexChange, label = "Tabs", className }: { tabs: SwipeTab[]; index?: number; defaultIndex?: number; onIndexChange?: (index: number) => void; label?: string; className?: string }) { const [current, setCurrent] = useControllable(index, defaultIndex, onIndexChange); const start = useRef<number | null>(null); const set = (next: number) => setCurrent(Math.max(0, Math.min(tabs.length - 1, next))); const active = tabs[current]; return <div className={className}><div role="tablist" aria-label={label} className="flex gap-1 overflow-x-auto border-b border-line">{tabs.map((tab, tabIndex) => <button key={tab.id} type="button" role="tab" aria-selected={tabIndex === current} onClick={() => set(tabIndex)} onKeyDown={(event) => { if (event.key === "ArrowRight" || event.key === "ArrowLeft") { event.preventDefault(); set(tabIndex + (event.key === "ArrowRight" ? 1 : -1)); } }} className={cn("shrink-0 border-b-2 px-4 py-3 text-sm", tabIndex === current ? "border-ink-900 font-semibold" : "border-transparent text-ink-500")}>{tab.label}</button>)}</div><motion.div role="tabpanel" tabIndex={0} onPointerDown={(event) => { start.current = event.clientX; }} onPointerUp={(event) => { if (start.current != null && Math.abs(event.clientX - start.current) > 60) set(current + (event.clientX < start.current ? 1 : -1)); start.current = null; }} className="touch-pan-y py-5">{active?.panel}</motion.div></div>; }

export type PullState = "idle" | "pulling" | "ready" | "refreshing" | "complete";
export function PullToRefresh({ onRefresh, children, threshold = 64, label = "Refresh content", className }: { onRefresh: () => Promise<void> | void; children: ReactNode; threshold?: number; label?: string; className?: string }) { const [state, setState] = useState<PullState>("idle"); const start = useRef<number | null>(null); const node = useRef<HTMLDivElement>(null); const frame = useRef<number | null>(null); const finish = async () => { setState("refreshing"); try { await onRefresh(); setState("complete"); } finally { window.setTimeout(() => setState("idle"), 700); } }; useEffect(() => () => { if (frame.current) cancelAnimationFrame(frame.current); }, []); return <div ref={node} className={cn("relative", className)} onPointerDown={(event) => { if ((node.current?.scrollTop ?? 0) === 0) start.current = event.clientY; }} onPointerMove={(event) => { if (start.current == null) return; const distance = Math.max(0, event.clientY - start.current); if (distance > 8) { setState(distance >= threshold ? "ready" : "pulling"); if (frame.current) cancelAnimationFrame(frame.current); frame.current = requestAnimationFrame(() => { if (node.current) node.current.style.setProperty("--pull-offset", `${Math.min(distance, threshold + 24)}px`); }); } }} onPointerUp={(event) => { const distance = start.current == null ? 0 : event.clientY - start.current; start.current = null; node.current?.style.setProperty("--pull-offset", "0px"); if (distance >= threshold) void finish(); else setState("idle"); }}><div role="status" aria-label={label} aria-live="polite" className="h-0 overflow-visible text-center text-xs text-ink-500" style={{ transform: "translateY(var(--pull-offset, 0px))" }}>{state === "ready" ? "Release to refresh" : state === "refreshing" ? "Refreshing…" : state === "complete" ? "Updated" : state === "pulling" ? "Pull to refresh" : null}</div>{children}</div>; }

export function EdgeSwipePanel({ edge = "left", open, defaultOpen = false, onOpenChange, children, label = "Panel", threshold = 80 }: { edge?: "left" | "right"; open?: boolean; defaultOpen?: boolean; onOpenChange?: (open: boolean) => void; children: ReactNode; label?: string; threshold?: number }) { const [shown, setShown] = useControllable(open, defaultOpen, onOpenChange); const start = useRef<number | null>(null); const onDown = (event: ReactPointerEvent) => { if (event.pointerType === "touch") start.current = event.clientX; }; const onUp = (event: ReactPointerEvent) => { if (start.current == null) return; const distance = edge === "left" ? event.clientX - start.current : start.current - event.clientX; if (distance > threshold) setShown(true); start.current = null; }; return <><div aria-hidden className="fixed inset-y-0 z-[60] w-3" style={{ [edge]: 0 }} onPointerDown={onDown} onPointerUp={onUp} /><button type="button" onClick={() => setShown(true)} className="rounded-full border border-line px-4 py-2 text-sm">Open {label}</button><AnimatePresence>{shown ? <motion.div className="fixed inset-0 z-[70] flex bg-ink-900/30" onMouseDown={(event) => { if (event.target === event.currentTarget) setShown(false); }}><motion.aside role="dialog" aria-label={label} className={cn("h-full w-[min(22rem,88vw)] bg-white p-5 shadow-2xl", edge === "right" ? "ml-auto" : "mr-auto")} initial={{ x: edge === "left" ? "-100%" : "100%" }} animate={{ x: 0 }} exit={{ x: edge === "left" ? "-100%" : "100%" }}><div className="flex justify-end"><button type="button" aria-label={`Close ${label}`} onClick={() => setShown(false)}>×</button></div>{children}</motion.aside></motion.div> : null}</AnimatePresence></>; }

export function LongPressAction({ children, onLongPress, duration = 500, onClick, label, className }: { children: ReactNode; onLongPress: () => void; duration?: number; onClick?: () => void; label?: string; className?: string }) { const timer = useRef<number | null>(null); const fired = useRef(false); const clear = () => { if (timer.current) window.clearTimeout(timer.current); timer.current = null; }; const start = () => { fired.current = false; clear(); timer.current = window.setTimeout(() => { fired.current = true; onLongPress(); }, duration); }; return <button type="button" aria-label={label} className={className} onPointerDown={start} onPointerUp={() => { clear(); if (!fired.current) onClick?.(); }} onPointerLeave={clear} onPointerCancel={clear} onContextMenu={(event) => { event.preventDefault(); clear(); onLongPress(); }} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onClick?.(); } }}>{children}</button>; }
